import {expect,test,type Page} from '@playwright/test';
import {writeFile,mkdir} from 'node:fs/promises';
import type {components} from '../../packages/api-client/src/schema.js';
const fixture='http://127.0.0.1:3036';
type Info={personalUser:string;staffUser:string;password:string;companyCode:string;personalDay:string;companyDay:string;hiddenTask:string;hiddenBranch:string;baselineForecast:string};
async function login(page:Page,info:Info,kind:'personal'|'company'){
 await page.goto(kind==='personal'?'/login/independent':'/login/company');if(kind==='personal')await page.getByLabel('رقم الهاتف').fill(info.personalUser);else{await page.getByLabel('كود الشركة (مطلوب)').fill(info.companyCode);await page.getByRole('button',{name:'متابعة',exact:true}).click();}
 await page.getByRole('button',{name:'متابعة تسجيل الدخول'}).click();await page.locator('#username').fill(kind==='personal'?info.personalUser:info.staffUser);await page.locator('#password').fill(info.password);await page.locator('#kc-login').click();await expect(page.getByRole('heading',{name:'حسابي'})).toBeVisible();
}
test.afterAll(async()=>{await writeFile('.local/phase-36-browser.stop','stop');});
test('mobile driver summary -> forecast/history; desktop scoped staff filters, reload and live revocation',async({browser,request})=>{
 const info=await(await request.get(`${fixture}/__fixture/info`)).json() as Info,reports:components['schemas']['ReportWorkday'][]=[];
 const personalContext=await browser.newContext({baseURL:'http://localhost:5173',viewport:{width:390,height:844},locale:'ar-EG',timezoneId:'Africa/Cairo',reducedMotion:'reduce'}),personal=await personalContext.newPage();await login(personal,info,'personal');
 // Labelled discovery outage includes StrictMode duplicate reads; retry uses the real API.
 await personal.route('**/api/v1/reports/workdays?kind=personal',route=>route.fulfill({status:503,contentType:'application/problem+json',body:JSON.stringify({detail:'تعذر الاتصال مؤقتًا',code:'dependency_unavailable'})}));
 await personal.getByRole('link',{name:'تقارير أيام العمل'}).click();await expect(personal.getByRole('alert')).toContainText('تعذر الاتصال مؤقتًا');await personal.unroute('**/api/v1/reports/workdays?kind=personal');await personal.getByRole('button',{name:'إعادة المحاولة',exact:true}).click();await expect(personal.getByRole('heading',{name:'تمت معالجة 2 من 4 شحنة'})).toBeVisible();
 const readPersonal=async()=>await(await personalContext.request.get(`/api/v1/reports/workdays/${info.personalDay}?kind=personal`)).json() as components['schemas']['ReportWorkday'];
 reports.push(await readPersonal());expect(reports[0]!.timing[0]!.baseline!.forecastId).toBe(info.baselineForecast);
 await expect(personal.getByText('التوقع والتنفيذ',{exact:true})).toBeVisible();expect(await personal.locator('body').innerText()).not.toContain('حالة قطع الشحنات');
 await personal.screenshot({path:'output/playwright/phase-36-driver-summary-mobile.png',fullPage:true});
 await personal.locator('.report-round > summary').click();await expect(personal.getByText('تغيّر العمل بعد البداية',{exact:true})).toBeVisible();await expect(personal.getByRole('heading',{name:'توقع البداية',exact:true})).toBeVisible();await expect(personal.getByRole('heading',{name:'آخر توقع محفوظ',exact:true})).toBeVisible();await expect(personal.getByText('انتهت الجولة وبها عمل متبقٍ',{exact:true})).toHaveCount(0);await expect(personal.getByText('عمل الجولة غير مكتمل',{exact:true}).first()).toBeVisible();
 await personal.locator('.report-results > summary').click();await personal.locator('.report-attempt').filter({hasText:'عميل 2'}).locator(':scope > summary').click();await expect(personal.getByText('وقت تقريبي',{exact:false}).first()).toBeVisible();await expect(personal.getByText('الوقت غير مسجّل',{exact:true}).first()).toBeVisible();
 await personal.locator('.report-round > summary').focus();await personal.keyboard.press('Enter');await expect(personal.locator('.report-round')).not.toHaveAttribute('open','');await personal.keyboard.press('Enter');await expect(personal.locator('.report-round')).toHaveAttribute('open','');
 await personal.screenshot({path:'output/playwright/phase-36-timing-mobile.png',fullPage:true});
 expect((await request.post(`${fixture}/__fixture/correct-close`)).ok()).toBe(true);await personal.getByRole('button',{name:'تحديث النتائج المقبولة'}).click();await expect(personal.getByText('2 تسليم كامل · 50% من الشحنات المعروضة',{exact:true})).toBeVisible();await personal.locator('.report-round > summary').click();await expect(personal.getByText('انتهت الجولة وبها عمل متبقٍ',{exact:true}).first()).toBeVisible();
 reports.push(await readPersonal());expect(reports[1]!.snapshotId).not.toBe(reports[0]!.snapshotId);expect(reports[1]!.timing[0]!.closure).toBe('ended-unfinished');
 await personal.locator('.report-results > summary').click();const corrected=personal.locator('.report-attempt').filter({hasText:'عميل 2'});await corrected.locator(':scope > summary').click();await corrected.getByText('النتيجة الأصلية والتصحيحات (2)',{exact:true}).click();await expect(corrected.getByText(/الأصل · لم يرد/)).toBeVisible();await expect(corrected.getByText(/تصحيح 1 · تسليم كامل/)).toBeVisible();
 for(const width of [320,390]){await personal.setViewportSize({width,height:844});expect(await personal.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
 await personal.screenshot({path:'output/playwright/phase-36-correction-mobile.png',fullPage:true});await personalContext.close();
 const staffContext=await browser.newContext({baseURL:'http://localhost:5173',viewport:{width:1440,height:900},locale:'ar-EG',timezoneId:'Africa/Cairo',reducedMotion:'reduce'}),staff=await staffContext.newPage();await login(staff,info,'company');await staff.getByRole('link',{name:'تقارير أيام العمل'}).click();await expect(staff.getByRole('heading',{name:'تمت معالجة 2 من 2 شحنة'})).toBeVisible();
 const staffReport=await(await staffContext.request.get(`/api/v1/reports/workdays/${info.companyDay}?kind=company`)).json() as components['schemas']['ReportWorkday'];reports.push(staffReport);expect(JSON.stringify(staffReport)).not.toContain(info.hiddenTask);expect(staffReport.timing[0]!.baseline).toBeNull();
 await staff.locator('.report-round > summary').click();await expect(staff.getByText('المعروض جزء من الجولة ضمن صلاحياتك',{exact:true}).first()).toBeVisible();await staff.getByLabel('النتيجة',{exact:true}).selectOption('partial');await staff.getByRole('button',{name:'عرض التقرير',exact:true}).click();await expect(staff.getByRole('heading',{name:'تمت معالجة 1 من 1 شحنة'})).toBeVisible();await expect(staff.getByText(/المعروض 1 من 2 شحنة/)).toBeVisible();
 await staff.reload();await expect(staff.getByRole('heading',{name:'تمت معالجة 1 من 1 شحنة'})).toBeVisible();await expect(staff.getByLabel('النتيجة',{exact:true})).toHaveValue('partial');await staff.screenshot({path:'output/playwright/phase-36-staff-desktop.png',fullPage:true});
 const foreign=(await staffContext.request.get(`/api/v1/reports/workdays/${info.personalDay}?kind=company`)).status(),branch=(await staffContext.request.get(`/api/v1/reports/workdays/${info.companyDay}?kind=company&branchId=${info.hiddenBranch}`)).status();expect(foreign).toBe(404);expect(branch).toBe(403);
 expect((await request.post(`${fixture}/__fixture/revoke-reports`)).ok()).toBe(true);await staff.getByRole('button',{name:'تحديث النتائج المقبولة'}).click();await expect(staff.getByRole('alert')).toContainText('التقرير غير متاح ضمن صلاحيات هذا الحساب.');await expect(staff.getByRole('heading',{name:'التحصيل المسجّل'})).toHaveCount(0);await staff.screenshot({path:'output/playwright/phase-36-report-denied.png',fullPage:true});await staffContext.close();
 await mkdir('.local',{recursive:true});await writeFile('.local/phase-36-browser-evidence.json',JSON.stringify({evidenceClass:'Actual local Keycloak/Chromium/Fastify/isolated PostgreSQL, controlled HTTP routing fixture and labelled public ERP source work; no physical-device claim',reports,authorization:{foreign,branch}},null,2));
});

