import { expect, test, type Page } from '@playwright/test';
import { writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
const fixture = 'http://127.0.0.1:3031';
type Info = { companyUser: string; personalUser: string; staffUser: string; password: string; companyCode: string; companyDriverId: string; taskIds: Record<string, string> };
async function login(page: Page, info: Info, kind: 'company' | 'personal', start = true) {
  await page.goto(kind === 'company' ? '/login/company' : '/login/independent');
  if (kind === 'company') { await page.getByLabel('كود الشركة (مطلوب)').fill(info.companyCode); await page.getByRole('button', { name: 'متابعة', exact: true }).click(); }
  else await page.getByLabel('رقم الهاتف').fill(info.personalUser);
  await page.getByRole('button', { name: 'متابعة تسجيل الدخول' }).click(); await page.locator('#username').fill(kind === 'company' ? info.companyUser : info.personalUser); await page.locator('#password').fill(info.password); await page.locator('#kc-login').click();
  await page.goto(`/prepare?kind=${kind}`);
  if (start) { await expect(page.getByText('خطة جاهزة')).toBeVisible(); await page.getByRole('button', { name: 'ابدأ الجولة' }).click(); await expect(page.getByRole('heading', { name: 'المحطة الحالية' })).toBeVisible(); }
}
async function choose(page: Page, name: string) { await page.getByRole('list', { name: 'قائمة المحطات المتاحة' }).getByRole('button', { name: new RegExp(name) }).click(); await expect(page.getByRole('region', { name: 'تفاصيل المحطة' }).getByRole('heading', { name, exact: true })).toBeVisible(); }
async function capture(page: Page, name: string) { await page.evaluate(() => document.fonts.ready); await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); await page.screenshot({ path: `output/playwright/phase-31-${name}.png`, fullPage: true }); }
test.afterAll(async () => { await writeFile('.local/phase-31-browser.stop', 'stop'); await expect.poll(() => existsSync('.local/phase-31-browser.stop'), { timeout: 30000 }).toBe(false); });

test('driver offer → native ERP actual subset → same-round resume, second-phone takeover and held day continuation', async ({ browser, request }) => {
  const info = await (await request.get(`${fixture}/__fixture/info`)).json() as Info;
  const context = await browser.newContext({ baseURL: 'http://localhost:5173', viewport: { width: 390, height: 844 }, locale: 'ar-EG', timezoneId: 'Africa/Cairo', reducedMotion: 'reduce' });
  const page = await context.newPage(), publicViews: { url: string; data: unknown }[] = [], reads: Promise<void>[] = [], unavailableResponseBodies: string[] = [];
  function record(tab: Page) { tab.on('response', response => { if (response.ok() && /\/api\/v1\/(returns\/(groups|requests)|workdays\/|current\/rounds\/|devices\/rounds\/)/.test(response.url())) reads.push(response.json().then(data => { publicViews.push({ url: response.url(), data }); }).catch(() => { unavailableResponseBodies.push(response.url()); })); }); }
  record(page); await login(page, info, 'company');
  await choose(page, 'عميل المرتجع'); await page.getByRole('button', { name: 'اتجه للعميل' }).click(); await page.getByRole('button', { name: 'لم يرد العميل', exact: true }).click();
  await expect(page.getByText(/تم تسجيل عدم الرد من الخادم/)).toBeVisible(); await choose(page, 'العميل المتوقف'); await page.getByRole('button', { name: 'اتجه للعميل' }).click(); await page.getByRole('button', { name: 'وصلت', exact: true }).click();
  await page.getByRole('link', { name: 'الإرجاع وزيارة الفرع' }).click(); await expect(page.getByText('سجّل نتيجة العميل أولًا', { exact: true })).toBeVisible(); await page.getByRole('link', { name: 'العودة للعميل الحالي' }).click(); await page.getByRole('button', { name: /تأكيد التسليم وتحصيل/ }).click();
  await expect(page.getByText(/تم تأكيد التسليم والتحصيل/)).toBeVisible(); await choose(page, 'عميل اليوم التالي'); await page.getByRole('button', { name: 'اتجه للعميل' }).click(); await page.getByRole('link', { name: 'الإرجاع وزيارة الفرع' }).click();
  await page.getByLabel('الكمية المعروضة — return/pieces').fill('3'); await page.getByRole('button', { name: 'أرسل طلب الإرجاع' }).click(); await page.getByLabel('القطع المطلوب تأكيدها — return/pieces').fill('2');
  await capture(page, 'offer-390'); await page.getByRole('button', { name: 'اتجه للفرع واحفظ ترتيب العملاء' }).click(); await expect(page.getByText('عميل اليوم التالي — أوقفنا الاتجاه إليه')).toBeVisible();
  await page.route('**/api/v1/branches/commands/branch.recordArrival?*', async route => { const committed = await route.fetch(); expect(committed.ok()).toBe(true); await route.abort('failed'); }, { times: 1 });
  await page.getByRole('button', { name: 'وصلت للفرع' }).click(); await expect(page.getByText('الطلب ينتظر التأكيد', { exact: true })).toBeVisible(); await page.reload(); await page.getByRole('button', { name: 'تحقّق من الطلب نفسه' }).click(); await expect(page.getByText('الطلب ينتظر التأكيد', { exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'استأنف الجولة' })).toBeDisabled(); await capture(page, 'waiting-390');
  // A separate installation sees the same branch stage and explicitly takes over.
  const secondContext = await browser.newContext({ baseURL: 'http://localhost:5173', viewport: { width: 390, height: 844 }, locale: 'ar-EG', reducedMotion: 'reduce' }), second = await secondContext.newPage(); record(second);
  await login(second, info, 'company', false); await expect(second.getByRole('button', { name: 'ابدأ الجولة' })).toHaveCount(0); await second.getByRole('link', { name: 'متابعة الجولة' }).click();
  await expect(second.getByText('الجولة تعمل على هاتف آخر', { exact: true })).toBeVisible(); await capture(second, 'other-phone-390'); await second.getByRole('button', { name: 'انقل التنفيذ لهذا الهاتف' }).click(); await expect(second.getByText('اكتمل نقل التنفيذ وتحميل الحالة المؤكدة لهذا الهاتف.', { exact: true })).toBeVisible();
  await second.reload(); await second.getByRole('link', { name: 'متابعة زيارة الفرع' }).click(); await expect(second.getByRole('button', { name: 'استأنف الجولة' })).toBeDisabled();
  await page.getByRole('button', { name: 'تحديث حالة الفرع' }).click(); await expect(page.getByText('الجولة تعمل على هاتف آخر', { exact: true })).toBeVisible();
  // Native staff confirmation uses the separate mock's real session/form/outbox.
  const staffContext = await browser.newContext({ viewport: { width: 1366, height: 900 }, locale: 'ar-EG', reducedMotion: 'reduce' }), staff = await staffContext.newPage();
  await staff.goto('http://localhost:5191'); await staff.getByRole('link', { name: 'دخول موظف ERP' }).click(); await staff.locator('#username').fill(info.staffUser); await staff.locator('#password').fill(info.password); await staff.locator('#kc-login').click();
  await staff.getByRole('tab', { name: 'مرتجعات المندوب' }).click(); await staff.getByLabel('مندوب المرتجعات').selectOption(info.companyDriverId); await staff.getByLabel('فرع الاستلام الأصلي').selectOption({ index: 1 }); await staff.getByRole('button', { name: 'عرض وتحديث المرتجعات' }).click();
  await staff.getByLabel('القطع الآن — return', { exact: true }).fill('2'); await staff.getByLabel('أؤكد استلام هذه القطع فعلًا').check(); await staff.getByRole('button', { name: 'تأكيد القطع المستلمة فقط' }).click(); await expect(staff.getByText('قبله توصيل.', { exact: true })).toBeVisible(); await staff.getByRole('button', { name: 'عرض وتحديث المرتجعات' }).click(); await expect(staff.getByText('مستلم: 2 · معلق: 1 · مفقود: 0 · تالف: 0')).toBeVisible(); await capture(staff, 'native-subset-1366');
  await second.getByRole('button', { name: 'تحديث حالة الفرع' }).click(); await expect(second.getByText('أكد الفرع القطع المحددة', { exact: true })).toBeVisible(); await expect(second.getByText('المتبقي معك: 1 قطعة')).toBeVisible(); await second.setViewportSize({ width: 320, height: 800 }); await capture(second, 'subset-320');
  await second.getByRole('button', { name: 'استأنف الجولة' }).click(); await expect(second.getByText('ترتيب العملاء المحفوظ (1)')).toHaveCount(0); await second.getByRole('link', { name: 'العودة للجولة', exact: true }).click(); await expect(second.getByRole('button', { name: 'اتجه للعميل' })).toBeVisible(); await second.getByRole('button', { name: 'اتجه للعميل' }).click();
  await second.getByRole('link', { name: 'ملخص العمل وإنهاء الجولة أو اليوم' }).click(); await expect(second.getByText('العمل المحتفظ به (2)', { exact: true })).toBeVisible(); await expect(second.getByRole('button', { name: 'إنهاء الجولة فقط' })).toBeDisabled(); await second.getByLabel('أوقف الاتجاه للعميل الحالي وأحتفظ بمهمته').check();
  await second.setViewportSize({ width: 390, height: 844 }); await capture(second, 'closure-390'); await second.getByRole('button', { name: 'إنهاء الجولة فقط' }).click(); await expect(second.getByText('انتهت الجولة — اليوم مفتوح', { exact: true })).toBeVisible(); await second.reload(); await expect(second.getByRole('button', { name: 'إنهاء يوم العمل' })).toBeEnabled();
  await second.route('**/api/v1/closure/day?*', async route => { const committed = await route.fetch(); expect(committed.ok()).toBe(true); await route.abort('failed'); }, { times: 1 });
  await second.getByRole('button', { name: 'إنهاء يوم العمل' }).click(); await expect(second.getByText('الإنهاء لم يتأكد بعد', { exact: true })).toBeVisible();
  await second.goto('/prepare?kind=company'); await expect(second.getByText('تحقّق من الإجراءات السابقة قبل بدء جولة', { exact: true })).toBeVisible(); await expect(second.getByRole('button', { name: 'ابدأ الجولة' })).toBeDisabled(); await second.getByRole('link', { name: 'فتح الإجراء المعلّق' }).click();
  await second.reload(); await second.getByRole('button', { name: 'تحقّق من الإنهاء نفسه' }).click(); await expect(second.getByText('الإنهاء لم يتأكد بعد', { exact: true })).toHaveCount(0); await expect(second.getByText('انتهى يوم العمل', { exact: true })).toBeVisible(); await capture(second, 'ended-day-390');
  await second.getByRole('link', { name: 'العودة لعمل اليوم' }).click(); await expect(second.getByRole('heading', { name: 'عميل اليوم التالي', exact: true })).toBeVisible(); await expect(second.getByRole('heading', { name: 'عميل المرتجع', exact: true })).toBeVisible();
  await second.goto('/prepare?kind=company'); await second.getByRole('button', { name: 'احفظ وجهّز المعاينة' }).click(); await expect(second.getByText('خطة جاهزة', { exact: true })).toBeVisible(); await second.getByRole('button', { name: 'ابدأ الجولة' }).click(); await expect(second.getByRole('heading', { name: 'المحطة الحالية' })).toBeVisible();
  const personalContext = await browser.newContext({ baseURL: 'http://localhost:5173', viewport: { width: 390, height: 844 }, locale: 'ar-EG', reducedMotion: 'reduce' }), personal = await personalContext.newPage(); record(personal); await login(personal, info, 'personal');
  await expect(personal.getByRole('link', { name: 'الإرجاع وزيارة الفرع' })).toHaveCount(0); await personal.getByRole('link', { name: 'ملخص العمل وإنهاء الجولة أو اليوم' }).click(); await expect(personal.getByText('العمل المحتفظ به (2)', { exact: true })).toBeVisible(); expect(await personal.locator('main').innerText()).not.toMatch(/قطعة|فرع|نظام الشركة|الشحن/); await personal.getByLabel('نطاق الإنهاء').selectOption('day'); await personal.getByRole('button', { name: 'إنهاء يوم العمل' }).click(); await expect(personal.getByText('انتهى يوم العمل', { exact: true })).toBeVisible(); await capture(personal, 'personal-closure-390');
  const state = await (await request.get(`${fixture}/__fixture/state`)).json();
  const rounds = state.rounds.filter((r: { driver_id: string }) => r.driver_id === info.companyDriverId); expect(rounds).toHaveLength(2); expect(rounds[0].workday_id).not.toBe(rounds[1].workday_id); expect(Number(rounds[0].device_generation)).toBe(2);
  for (const op of ['return.requestHandover', 'branch.interruptRound', 'branch.recordArrival', 'branch.resumeRound', 'device.takeOver', 'round.end']) expect(state.actions.filter((a: { operation_id: string; business_status: string }) => a.operation_id === op && a.business_status === 'accepted')).toHaveLength(1);
  const native = await staff.evaluate(async () => (await fetch('/native/state')).json()); expect(native.commands.filter((c: { envelope: { operationId: string }; status: string }) => c.envelope.operationId === 'return.confirmSubsetReceipt' && c.status === 'accepted')).toHaveLength(1);
  await Promise.all(reads); await writeFile('.local/phase-31-browser-evidence.json', JSON.stringify({ evidenceClass: 'Real local Keycloak, Chromium, Fastify, PostgreSQL and native ERP form/source worker in separate process/database. Controlled routing and initial source fixtures. Browser contexts are logical phones, not physical-device evidence.', publicViews, unavailableResponseBodies, state }, null, 2));
  await personalContext.close(); await staffContext.close(); await secondContext.close(); await context.close();
});
