import {test,expect} from '@playwright/test';
test.afterAll(async({request})=>{expect((await request.post('http://127.0.0.1:3011/__fixture/cleanup')).ok()).toBe(true);});
test('real maps, explicit candidate/manual confirmation, keyboard/touch and failed tiles preserve input',async({page,context,request})=>{
 await page.setViewportSize({width:390,height:844});
 const ranges:string[]=[],glyphs:string[]=[],external:string[]=[];
 page.on('response',r=>{if(r.url().includes('cairo.pmtiles')&&r.status()===206)ranges.push(r.url());if(r.url().includes('/fonts/')&&r.status()===200)glyphs.push(r.url());});
 page.on('request',r=>{if(!new URL(r.url()).hostname.match(/^(localhost|127\.0\.0\.1)$/))external.push(r.url());});
 await page.addInitScript(()=>{Object.defineProperty(navigator,'geolocation',{value:{getCurrentPosition(){throw new Error('Forbidden GPS request');},watchPosition(){throw new Error('Forbidden GPS watch');}}});});
 await page.goto('/tasks');await page.locator('.task-card').filter({hasText:'منى'}).getByRole('link',{name:'مراجعة الموقع'}).click();
 await expect(page.getByRole('heading',{name:'راجع الموقع وأكّد النقطة'})).toBeVisible();
 await expect(page.getByRole('button',{name:'اختيار وسط الخريطة'})).toBeEnabled({timeout:60000});
 await expect.poll(()=>ranges.length).toBeGreaterThan(0);await expect.poll(()=>glyphs.length).toBeGreaterThan(0);
 await page.locator('.pin-map').scrollIntoViewIfNeeded();await page.screenshot({path:'output/playwright/phase-11-map-mobile.png',fullPage:true});
 await page.getByRole('button',{name:'بحث',exact:true}).click();await expect(page.getByRole('radio')).toHaveCount(2);
 await expect(page.getByRole('button',{name:'تأكيد نقطة التوصيل'})).toBeDisabled();
 await page.getByRole('radio').first().check();
 let loseResponse=true;
 await page.route('**/api/v1/locations/*?kind=personal',async route=>{if(loseResponse&&route.request().method()==='PUT'){loseResponse=false;await route.fetch();await route.abort();}else await route.continue();});
 await page.getByRole('button',{name:'تأكيد نقطة التوصيل'}).click();await expect(page.getByText(/تعذر الاتصال. المدخلات/)).toBeVisible();
 await page.reload();await page.getByRole('button',{name:'تأكيد نقطة التوصيل'}).click();await expect(page.getByText('تم تأكيد الموقع',{exact:true})).toBeVisible();
 const replayed=await page.request.get(`/api/v1/locations/${new URL(page.url()).pathname.split('/')[2]}?kind=personal`);expect((await replayed.json()).locationRevision).toBe(1);
 await page.reload();await expect(page.getByText(/الموقع الحالي مؤكّد/)).toBeVisible();
 await page.getByLabel('ابحث عن العنوان').fill('فارغ');await page.getByRole('button',{name:'بحث',exact:true}).click();await expect(page.getByText(/لا توجد نتائج/)).toBeVisible();
 await page.getByLabel('ابحث عن العنوان').fill('فشل');await page.getByRole('button',{name:'بحث',exact:true}).click();await expect(page.getByText(/تعذر البحث عن العنوان/)).toBeVisible();await expect(page.getByText(/الموقع الحالي مؤكّد/)).toBeVisible();
 await expect(page.getByRole('button',{name:'اختيار وسط الخريطة'})).toBeEnabled({timeout:60000});await page.locator('.maplibregl-canvas').focus();await page.keyboard.press('ArrowRight');await page.getByRole('button',{name:'اختيار وسط الخريطة'}).focus();await page.keyboard.press('Enter');await page.getByRole('button',{name:'تأكيد نقطة التوصيل'}).click();await expect(page.getByText('تم تأكيد الموقع',{exact:true})).toBeVisible();
 await page.setViewportSize({width:1366,height:900});await page.getByRole('button',{name:'تكبير',exact:true}).click({clickCount:2});await page.waitForTimeout(1000);await page.screenshot({path:'output/playwright/phase-11-map-desktop.png',fullPage:true});
 const range=await request.get('/maps/cairo.pmtiles',{headers:{Range:'bytes=0-126'}});expect(range.status()).toBe(206);expect((await range.body()).subarray(0,7).toString()).toBe('PMTiles');expect(range.headers()['content-range']).toMatch(/^bytes 0-126\//);
 expect((await request.get('/maps/cairo.pmtiles',{headers:{Range:'bytes=99999999999-'}})).status()).toBe(416);
 expect(external).toEqual([]);
 await page.route('**/maps/cairo.pmtiles',route=>route.fulfill({status:503,body:'unavailable'}));
 await page.reload();await expect(page.getByText(/تعذر عرض بعض أجزاء الخريطة/)).toBeVisible({timeout:30000});await expect(page.getByText('العنوان الأصلي',{exact:true})).toBeVisible();
 await page.getByLabel('خط العرض',{exact:true}).fill('30.046');await page.getByLabel('خط الطول',{exact:true}).fill('31.236');await page.getByRole('button',{name:'استخدام الإحداثيات'}).click();await page.getByRole('button',{name:'تأكيد نقطة التوصيل'}).click();await expect(page.getByText('تم تأكيد الموقع',{exact:true})).toBeVisible();
 await page.setViewportSize({width:360,height:800});await page.screenshot({path:'output/playwright/phase-11-tile-failure.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.getByRole('link',{name:'العودة',exact:true}).click();await expect(page.getByText('عميل آخر — عمل مستقل')).toBeVisible();await expect(page.getByText('الموقع يحتاج تحديد')).toHaveCount(1);
 const touch=await context.browser()!.newContext({baseURL:'http://localhost:5177',hasTouch:true,viewport:{width:390,height:844},locale:'ar-EG'});const tp=await touch.newPage();await tp.goto('/tasks');await tp.locator('.task-card').filter({hasText:'منى'}).getByRole('link',{name:'مراجعة الموقع'}).tap();await expect(tp.getByRole('button',{name:'اختيار وسط الخريطة'})).toBeEnabled({timeout:60000});await tp.getByRole('button',{name:'اختيار وسط الخريطة'}).tap();await tp.getByRole('button',{name:'تأكيد نقطة التوصيل'}).tap();await expect(tp.getByText('تم تأكيد الموقع',{exact:true})).toBeVisible();await touch.close();
});
