import {useEffect,useMemo,useState} from 'react';
import {CalendarDays,ClipboardList,Download,FileSpreadsheet} from 'lucide-react';
import type {components} from '@tawsel/api-client';
import {ReportingClient,type ReportFilters} from '@tawsel/api-client/src/reporting';
import {formatWorkdayInstant} from '@tawsel/api-client/src/closure';
import {ActionButton,StatusNotice} from './components/ui';
import {useLocalPending} from './local-status';
type S=components['schemas'];
const labels:Record<string,string>={full:'تسليم كامل',partial:'تسليم جزئي',refused:'رفض الاستلام','no-answer':'لم يرد',unfinished:'لم تنتهِ',deferred:'مؤجلة'};
const reasons:Record<string,string>={'missing-boundary':'الوقت غير مسجّل','uncertain-clock':'ساعة الهاتف غير مؤكدة','clock-order':'ترتيب الأوقات غير موثوق','different-device':'تغيّر الهاتف بين الإجراءين',interrupted:'تخللت العمل وقفة أو زيارة فرع','changed-workload':'تغيّر العمل المطلوب',unfinished:'عمل الجولة غير مكتمل','scoped-view':'المعروض جزء من الجولة ضمن صلاحياتك','endpoint-unobserved':'الوصول لنقطة النهاية غير مسجّل','forecast-unavailable':'لا يوجد تقدير محفوظ','identity-changed':'تغيّرت بيانات المهمة أو مكانها','identity-unavailable':'بيانات مطابقة المهمة القديمة غير محفوظة'};
const date=(s:string|null)=>s?formatWorkdayInstant(s):'غير مسجّل';
export function reportMoney(minor:string,currency:string,exponent:number){const amount=BigInt(minor),scale=10n**BigInt(exponent);return `${(amount/scale).toLocaleString('ar-EG')}${exponent?'٫'+(amount%scale).toString().padStart(exponent,'0'):''} ${currency==='EGP'?'ج.م':currency}`;}
function actual(t:S['ReportTime']){return t.status==='missing'?'غير مسجّل':`${t.status==='uncertain'?'وقت تقريبي · ':''}${date(t.observedAt)}`;}
function measure(m:S['ReportMeasurement'],difference=false){if(m.seconds===null)return reasons[m.reason??'missing-boundary'];const seconds=Math.abs(m.seconds),value=seconds>=60?`${(seconds/60).toLocaleString('ar-EG',{maximumFractionDigits:1})} دقيقة`:`${seconds.toLocaleString('ar-EG',{maximumFractionDigits:1})} ثانية`;return difference?m.seconds===0?'مطابق للتوقع':`${m.seconds>0?'بعد':'قبل'} التوقع بـ ${value}`:value;}
function ForecastCard({label,f}:{label:string;f:S['ReportForecast']|null}){return <div className="report-forecast"><h4>{label}</h4>{f?<><strong>خطة {f.planRevision} · {f.customerAttempts} محاولة عميل{f.branchStops?` · ${f.branchStops} زيارة فرع`:''}</strong><p>حُفظ التوقع: <bdi>{date(f.capturedAt)}</bdi></p><p>النهاية المتوقعة: <bdi>{f.expectedFinishAt?date(f.expectedFinishAt):'التوقيت غير متاح لهذه الخطة'}</bdi></p><details className="report-reference"><summary>مرجع المقارنة</summary><p>التوقع: <bdi>{f.forecastId}</bdi></p><p>نطاق العمل: <bdi>{f.workloadId}</bdi></p></details></>:<p>التوقع الكامل غير متاح ضمن هذا العرض.</p>}</div>;}
function StopTiming({stop}:{stop:S['ReportStopTiming']}){return <section className="report-stop-timing"><h4>وصول وإكمال المحاولة</h4>{!stop.baseline?<p className="report-note">هذه المحاولة ليس لها توقع بداية محفوظ ضمن المقارنة.</p>:null}{stop.latest&&!stop.latest.identityMatches?<p className="report-note">تعذّرت مطابقة بيانات المهمة مع التوقع؛ فرق الوقت غير متاح.</p>:null}
 <div className="report-comparison" role="table" aria-label="توقع الوصول والإكمال"><div role="row" className="report-table-head"><span role="columnheader">الوقت</span><span role="columnheader">توقع البداية</span><span role="columnheader">آخر توقع قبل التنفيذ</span><span role="columnheader">ما سجّله المندوب</span></div>
 {([['الوصول','expectedArrivalAt','arrival'],['الإكمال','expectedCompletionAt','completion']] as const).map(([label,expected,time])=><div role="row" key={label}><strong role="rowheader">{label}</strong><span role="cell" data-label="توقع البداية"><bdi>{stop.baseline?.[expected]?date(stop.baseline[expected]):'غير متاح'}</bdi></span><span role="cell" data-label="آخر توقع"><bdi>{stop.latest?.[expected]?date(stop.latest[expected]):'غير متاح'}</bdi></span><span role="cell" data-label="المسجّل"><bdi>{actual(stop[time])}</bdi></span></div>)}</div>
 <dl className="report-detail-metrics"><div><dt>من الاتجاه إلى الوصول</dt><dd>{measure(stop.travel)}</dd></div><div><dt>من الوصول إلى الإكمال</dt><dd>{measure(stop.service)}</dd></div><div><dt>فارق الوصول عن آخر توقع</dt><dd>{measure(stop.latestArrivalDifference,true)}</dd></div><div><dt>فارق الإكمال عن آخر توقع</dt><dd>{measure(stop.latestCompletionDifference,true)}</dd></div></dl>
 <details className="report-reference"><summary>مصدر الأوقات والتوقعات</summary><p>الوصول إلى الخادم: <bdi>{date(stop.arrival.recordedAt)}</bdi>. هذا ليس وقت الوصول للعميل.</p><p>الاتجاه المسجّل: <bdi>{actual(stop.heading)}</bdi></p><p>إكمال التنفيذ الأصلي: <bdi>{actual(stop.completion)}</bdi></p>{stop.revisions.map(f=><p key={f.forecastId}>خطة {f.planRevision} · محفوظة <bdi>{date(f.capturedAt)}</bdi> · {f.membership==='paused'?'العمل موقوف لزيارة الفرع':f.expectedArrivalAt?'توقيت متوقع':'التوقيت غير متاح'}</p>)}</details>
 </section>;}
function RoundTiming({round,index}:{round:S['ReportRoundTiming'];index:number}){return <details className="report-round"><summary><span>الجولة {index+1} · مقارنة التوقيت</span><span>{round.closure==='open'?'نشطة':round.closure==='ended-unfinished'?`${round.unfinishedAttempts} محاولة لم تنتهِ`:round.closure==='scoped-view'?'جزء مصرح به':'انتهت المحاولات'}</span></summary>
 {round.visibility==='authorized-subset'?<StatusNotice title="المعروض جزء من الجولة ضمن صلاحياتك">توقيت الجولة الكاملة غير ظاهر هنا. افتح تفاصيل الشحنة لمقارنة محاولتها.</StatusNotice>:null}
 {round.scopeChanged?<StatusNotice tone="waiting" title="تغيّر العمل بعد البداية">التوقع الأول يخص العمل وقت البداية؛ التوقع الأخير يوضح العمل المعدّل. الفرق ليس حكمًا على أداء المندوب.</StatusNotice>:null}
 {round.interrupted?<p className="report-note">تخللت الجولة وقفة أو زيارة فرع؛ زمنها منفصل عن خدمة العملاء.</p>:null}
 {round.closure==='ended-unfinished'?<StatusNotice tone="waiting" title="انتهت الجولة وبها عمل متبقٍ">الإغلاق لا يعني إكمال نطاق توقع البداية.</StatusNotice>:null}
 <div className="report-forecast-grid"><ForecastCard label="توقع البداية" f={round.baseline}/><ForecastCard label="آخر توقع محفوظ" f={round.latest}/></div>
 <dl className="report-detail-metrics"><div><dt>بدء التنفيذ المسجّل</dt><dd><bdi>{actual(round.start)}</bdi></dd></div><div><dt>إنهاء التنفيذ المسجّل</dt><dd><bdi>{actual(round.end)}</bdi></dd></div><div><dt>الزمن بين البدء والإنهاء</dt><dd>{measure(round.elapsed)}</dd></div><div><dt>النهاية مقابل توقع البداية</dt><dd>{measure(round.baselineFinishDifference,true)}</dd></div><div><dt>النهاية مقابل آخر توقع</dt><dd>{measure(round.latestFinishDifference,true)}</dd></div></dl>
 {round.branchVisits.length?<section><h4>زيارات الفرع · {round.branchVisits.length} زيارة</h4>{round.branchVisits.map(b=><div className="report-forecast" key={b.segmentId}><p>مدة الخدمة المقدّرة: {b.serviceEstimateSeconds/60} دقيقة</p><p>الوصول: <bdi>{actual(b.arrival)}</bdi></p><p>العودة للعملاء: <bdi>{actual(b.completion)}</bdi></p><p>مدة الخدمة المسجّلة: {measure(b.service)}</p></div>)}</section>:null}
 <details className="report-reference"><summary>تواريخ قبول الخادم وسجل التوقعات</summary><p>قُبل البدء: <bdi>{date(round.acceptedStartAt)}</bdi></p><p>قُبل الإنهاء: <bdi>{date(round.acceptedEndAt)}</bdi></p>{round.revisions.map(f=><p key={f.forecastId}>خطة {f.planRevision} · {f.customerAttempts} محاولة · <bdi>{date(f.capturedAt)}</bdi></p>)}</details>
 </details>;}
export function ReportView({report,kind}:{report:S['ReportWorkday'];kind:'personal'|'company'}){
 const c=report.counts;
 return <div className="report-content"><section className="report-summary" aria-label="ملخص التقرير"><p>{report.endedAt?'يوم عمل منتهٍ':'يوم العمل مفتوح'}</p><h2>تمت معالجة {c.processedShipments} من {c.shipments} شحنة</h2><p>{c.fullShipments} تسليم كامل · {c.fullDeliveryPercent===null?'لا توجد شحنات':`${c.fullDeliveryPercent}% من الشحنات المعروضة`}</p><dl className={`report-summary-counts ${kind}`}>{kind==='company'?<div><dt>تسليم جزئي</dt><dd>{c.partialShipments}</dd></div>:null}<div><dt>رفض أو عدم رد</dt><dd>{c.refusedShipments+c.noAnswerShipments}</dd></div><div><dt>لم تنتهِ</dt><dd>{c.unfinishedShipments}</dd></div></dl><p className="report-denominator">{c.processedAttempts} محاولة بنتيجة من {c.attempts} محاولة · إعادة المحاولة لا تضيف شحنة.</p></section>
 {report.filters.outcome?<p className="report-note">التصفية: {labels[report.filters.outcome]} · المعروض {c.shipments} من {report.scopeCounts.shipments} شحنة في نطاق الجولة والفروع.</p>:null}
 {(c.unfinishedShipments||c.deferredShipments)?<StatusNotice tone="waiting" title="عمل لم ينتهِ">{c.unfinishedShipments} شحنة بلا نتيجة نهائية · {c.deferredShipments} مؤجلة. إغلاق اليوم لا يسجّل تسليمها.</StatusNotice>:null}
 <section className="report-section"><h2>التحصيل المسجّل</h2><p>مبالغ أبلغ عنها المندوب وقبلها الخادم؛ ليست تسوية مالية.</p>{report.collections.length?report.collections.map(m=><div className="report-collection" key={m.currency+':'+m.exponent}>{report.attempts.some(a=>a.outcome?.collection.reported?.currency===m.currency&&a.outcome.collection.reported.exponent===m.exponent)?<strong className="report-amount"><bdi>{reportMoney(m.reportedMinor,m.currency,m.exponent)}</bdi></strong>:<strong>لا توجد مبالغ مسجّلة</strong>}{kind==='company'?<dl className="report-detail-metrics"><div><dt>بضاعة</dt><dd><bdi>{reportMoney(m.goodsMinor,m.currency,m.exponent)}</bdi></dd></div><div><dt>شحن محصّل</dt><dd><bdi>{reportMoney(m.shippingMinor,m.currency,m.exponent)}</bdi></dd></div><div><dt>شحن رُفض دفعه ولم يُحصّل</dt><dd><bdi>{reportMoney(m.unpaidShippingMinor,m.currency,m.exponent)}</bdi></dd></div></dl>:null}{m.unreportedAttempts?<p>{m.unreportedAttempts} محاولة دون مبلغ مسجّل.</p>:null}</div>):<p>لا يوجد تحصيل مسجّل في هذا الاختيار.</p>}</section>
 {report.pieces?<details className="report-section"><summary>حالة قطع الشحنات الآن · {report.pieces.held} قطعة مع المندوب</summary><p>حالة دورات الشحن المختارة وقت عرض التقرير؛ قد يكون تأكيد الفرع وصل بعد يوم العمل.</p><dl className="report-detail-metrics">{([['dispatched','خرجت للتوصيل'],['delivered','سُلّمت للعميل'],['held','مع المندوب'],['returnRequired','منها مطلوب إرجاعه'],['received','استلمها الفرع فعلًا'],['lost','فقد مسجّل'],['damaged','تلف مسجّل']] as const).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{report.pieces![key]} قطعة</dd></div>)}</dl></details>:null}
 <section className="report-section"><h2>التوقع والتنفيذ</h2><p>افتح الجولة لمراجعة نطاق البداية والتوقع المعدّل. الأوقات بتوقيت القاهرة مع التاريخ.</p>{report.timing.map((r,i)=><RoundTiming key={r.roundId} round={r} index={i}/>)}</section>
 <details className="report-section report-results"><summary>نتائج الشحنات وتفاصيل المحاولات ({c.attempts})</summary>{report.attempts.length?report.attempts.map((item,i)=>{const stop=report.timing.find(r=>r.roundId===item.roundId)?.stops.find(s=>s.attemptId===item.attemptId);return <details className="report-attempt" key={item.attemptId}><summary><span>{i+1}. <bdi dir="auto">{item.recipientName}</bdi></span><span>{item.outcome?labels[item.outcome.outcome]:item.deferred?'مؤجلة':'لم تنتهِ'}</span></summary>
  <p>هذه محاولة مستقلة للشحنة. {item.outcome?`النتيجة المقبولة: ${labels[item.outcome.outcome]}.`:'لم تُقبل نتيجة لهذه المحاولة بعد.'}</p>{item.outcome?.collection.reported?<p>التحصيل: <bdi>{reportMoney(String(item.outcome.collection.reported.amountMinor),item.outcome.collection.reported.currency,item.outcome.collection.reported.exponent)}</bdi></p>:null}{stop?<StopTiming stop={stop}/>:null}
  <details className="report-reference"><summary>النتيجة الأصلية والتصحيحات ({item.history.length})</summary>{item.history.length?item.history.map((o,index)=><p key={o.outcomeId}>{index===0?'الأصل':`تصحيح ${index}`} · {labels[o.outcome]} · {o.collection.reported?reportMoney(String(o.collection.reported.amountMinor),o.collection.reported.currency,o.collection.reported.exponent):'دون مبلغ مسجّل'} · قُبل <bdi>{date(o.time.recordedAt)}</bdi>{index===item.history.length-1?' · النتيجة الحالية':''}</p>):<p>لا توجد نتيجة مقبولة.</p>}{item.returns.map(t=><p key={t.transitionId}>{t.quantity} قطعة · {t.kind==='received'?'استلمها الفرع':t.kind==='lost'?'فقد مسجّل':'تلف مسجّل'}</p>)}</details>
 </details>;}):<p>لا توجد نتائج بهذا الاختيار؛ عدّل التصفية.</p>}</details>
 </div>;
}
export function ReportingPage({initialWorkdayId}:{initialWorkdayId?:string}={}){
 const query=useMemo(()=>new URLSearchParams(location.search),[]),kind=query.get('kind')==='company'?'company':'personal',client=useMemo(()=>new ReportingClient(kind),[kind]),local=useLocalPending();
 const initialDay=initialWorkdayId??location.pathname.match(/^\/reports\/workdays\/([^/]+)$/)?.[1]??'';
 const initialFilters:ReportFilters={...(query.get('driverId')?{driverId:query.get('driverId')!}:{}),...(query.get('branchId')?{branchId:query.get('branchId')!}:{}),...(query.get('roundId')?{roundId:query.get('roundId')!}:{}),...(query.get('outcome')?{outcome:query.get('outcome') as NonNullable<ReportFilters['outcome']>}:{})};
 const [days,setDays]=useState<S['ReportDayList']|null>(null),[day,setDay]=useState(initialDay),[driver,setDriver]=useState(query.get('driverId')??''),[branch,setBranch]=useState(query.get('branchId')??''),[round,setRound]=useState(query.get('roundId')??''),[outcome,setOutcome]=useState(query.get('outcome')??'');
 const [selection,setSelection]=useState<{day:string;filters:ReportFilters}|null>(initialDay?{day:initialDay,filters:initialFilters}:null),[refresh,setRefresh]=useState(0),[listRevision,setListRevision]=useState(0),[report,setReport]=useState<S['ReportWorkday']|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[listing,setListing]=useState(true),[exportJob,setExportJob]=useState<S['ReportExportStatus']|null>(null),[exportBusy,setExportBusy]=useState<'create'|'download'|null>(null),[exportError,setExportError]=useState('');
 useEffect(()=>{setListing(true);const c=new AbortController(),filters={...(query.get('driverId')?{driverId:query.get('driverId')!}:{}),...(query.get('branchId')?{branchId:query.get('branchId')!}:{})};client.list(filters,c.signal).then(value=>{if(c.signal.aborted)return;setDays(value);if(!initialDay&&value.items[0]){setDay(value.items[0].workdayId);setSelection({day:value.items[0].workdayId,filters});}setListing(false);}).catch(e=>{if(!c.signal.aborted){setError(e?.status===403||e?.status===404?'التقرير غير متاح ضمن صلاحيات هذا الحساب.':e instanceof Error?e.message:'تعذر تحميل أيام العمل.');setListing(false);}});return()=>c.abort();},[client,listRevision]); // Selection changes do not restart day discovery.
 useEffect(()=>{if(!selection)return;const c=new AbortController();setBusy(true);setError('');setReport(null);client.workday(selection.day,selection.filters,c.signal).then(value=>{if(!c.signal.aborted)setReport(value);}).catch(e=>{if(!c.signal.aborted)setError(e?.status===403||e?.status===404?'التقرير غير متاح ضمن صلاحيات هذا الحساب.':e instanceof Error?e.message:'تعذر تحميل التقرير.');}).finally(()=>{if(!c.signal.aborted)setBusy(false);});return()=>c.abort();},[client,selection,refresh]);
 useEffect(()=>{setExportJob(null);setExportError('');setExportBusy(null);},[report?.snapshotId]);
 const drivers=[...new Map(days?.items.map(d=>[d.driverId,d])).values()],visibleDays=days?.items.filter(d=>!driver||d.driverId===driver)??[];
 const apply=()=>{if(!day)return;const filters:ReportFilters={...(driver?{driverId:driver}:{}),...(branch?{branchId:branch}:{}),...(round?{roundId:round}:{}),...(outcome?{outcome:outcome as NonNullable<ReportFilters['outcome']>}:{})};setSelection({day,filters});const q=new URLSearchParams({kind,...Object.fromEntries(Object.entries(filters).filter((x):x is [string,string]=>typeof x[1]==='string'))});history.replaceState(null,'',`/reports/workdays/${day}?${q}`);};
 const exportFilters=():ReportFilters=>report?{...(report.filters.driverId?{driverId:report.filters.driverId}:{}),...(report.filters.branchId?{branchId:report.filters.branchId}:{}),...(report.filters.roundId?{roundId:report.filters.roundId}:{}),...(report.filters.outcome?{outcome:report.filters.outcome}:{})}:{};
 const createExport=async()=>{if(!report)return;setExportBusy('create');setExportError('');try{setExportJob(await client.requestExcel(report.workdayId,report.snapshotId,exportFilters()));}catch(e){setExportJob(null);setExportError((e as {code?:string}).code==='snapshot_changed'?'تغيّرت النتائج منذ عرض التقرير. حدّث التقرير ثم أعد التصدير.':e instanceof Error?e.message:'تعذر إنشاء ملف Excel.');}finally{setExportBusy(null);}};
 const downloadExport=async()=>{if(!exportJob)return;setExportBusy('download');setExportError('');try{const {blob,fileName}=await client.downloadExcel(exportJob.exportId),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=fileName;document.body.append(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setExportJob(null);setExportError((e as {code?:string}).code==='export_expired'?'انتهت صلاحية الملف. أنشئ ملفًا جديدًا من التقرير الحالي.':e instanceof Error?e.message:'تعذر تنزيل ملف Excel.');}finally{setExportBusy(null);}};
 return <main className="report-shell" dir="rtl"><header className="tasks-header"><div><p className="eyebrow">توصيل · النتائج المقبولة</p><h1>تقرير يوم العمل</h1><p>راجع ما تم وما بقي، والتحصيل والتوقيت.</p></div><span className="tasks-logo" aria-hidden="true"><ClipboardList/></span></header>
 <form className="report-filters" onSubmit={e=>{e.preventDefault();apply();}}>{kind==='company'?<label>المندوب<select aria-label="المندوب" value={driver} onChange={e=>{setDriver(e.target.value);const next=days?.items.find(d=>!e.target.value||d.driverId===e.target.value);setDay(next?.workdayId??'');setRound('');}}><option value="">كل المندوبين المصرح بهم</option>{drivers.map(d=><option value={d.driverId} key={d.driverId}>{d.driverLabel}</option>)}</select></label>:null}
 <label>يوم العمل<select aria-label="يوم العمل" value={day} onChange={e=>{setDay(e.target.value);setRound('');}}><option value="">اختر يوم العمل</option>{initialDay&&!days?.items.some(d=>d.workdayId===initialDay)?<option value={initialDay}>يوم العمل المحدد</option>:null}{visibleDays.map(d=><option key={d.workdayId} value={d.workdayId}>{formatWorkdayInstant(d.openedAt)}{kind==='company'?` · ${d.driverLabel}`:''}</option>)}</select></label>
 {kind==='company'?<label>الفرع<select aria-label="الفرع" value={branch} onChange={e=>setBranch(e.target.value)}><option value="">كل الفروع المصرح بها</option>{days?.branches.map(b=><option key={b.branchId} value={b.branchId}>{b.label}</option>)}</select></label>:null}
 <details className="report-filter-details" open={kind==='company'||!!round||!!outcome}><summary>الجولة والنتيجة</summary><div className="report-filter-options"><label>الجولة<select aria-label="الجولة" value={round} onChange={e=>setRound(e.target.value)}><option value="">كل جولات اليوم</option>{report?.workdayId===day?report.rounds.map((r,i)=><option value={r.roundId} key={r.roundId}>الجولة {i+1} · {date(r.startedAt)}</option>):round?<option value={round}>الجولة المحددة</option>:null}</select></label>
 <label>النتيجة<select aria-label="النتيجة" value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="">كل النتائج</option>{Object.entries(labels).filter(([key])=>kind==='company'||key!=='partial').map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
 </div></details><ActionButton busy={busy} disabled={!day}>عرض التقرير</ActionButton></form>
 {days?.nextBefore?<ActionButton variant="quiet" onClick={()=>{void client.list({before:days.nextBefore!}).then(more=>setDays({...more,items:[...days.items,...more.items]})).catch(()=>setError('تعذر تحميل أيام أقدم.'));}}>أيام أقدم</ActionButton>:null}
 {local.kind===kind&&local.unreceived>0?<StatusNotice tone="waiting" title="إجراءات على الهاتف لم تدخل التقرير">{local.unreceived} إجراء ينتظر وصوله للخادم. <a href={`/local-work?kind=${kind}`}>مراجعة المزامنة</a></StatusNotice>:null}
 {error?<StatusNotice tone="error" title="تعذر عرض التقرير" live>{error} <ActionButton variant="quiet" onClick={()=>{if(!days)setListRevision(n=>n+1);setRefresh(n=>n+1);}}>إعادة المحاولة</ActionButton></StatusNotice>:null}
 {busy||listing?<StatusNotice title="جارٍ تحميل التقرير المصرح به" live/>:!days?.items.length&&!report&&!error?<StatusNotice title="لم يبدأ يوم عمل متاح بعد">ابدأ عملك ثم ارجع لعرض النتائج المقبولة.</StatusNotice>:null}
 {report?<><div className="report-period"><CalendarDays aria-hidden="true"/><div><p>بدأ: <bdi>{date(report.openedAt)}</bdi></p><p>{report.endedAt?<>انتهى: <bdi>{date(report.endedAt)}</bdi></>:'يوم العمل مستمر ولو تغيّر التاريخ.'}</p></div></div><ReportView report={report} kind={kind}/><p className="report-footnote">حالة الخادم وقت <bdi>{date(report.asOf)}</bdi>. الإجراءات غير المرسلة من الهواتف ليست ضمن الأرقام.</p><section className="report-export" aria-labelledby="report-export-title"><FileSpreadsheet aria-hidden="true"/><div><h2 id="report-export-title">تصدير نفس التقرير إلى Excel</h2><p>الملف يطابق التصفية والنتائج المقبولة الظاهرة الآن، ويذكر الوحدات وتوقيت القاهرة. أي إجراءات لم تصل للخادم لن تدخل الملف.</p>{exportError?<StatusNotice tone="error" title="تعذر تصدير التقرير" live>{exportError}</StatusNotice>:null}{exportJob?.status==='ready'?<StatusNotice tone="success" title="ملف Excel جاهز" live>صالح للتنزيل حتى <bdi>{date(exportJob.expiresAt)}</bdi>. <ActionButton variant="quiet" busy={exportBusy==='download'} onClick={()=>void downloadExport()}><Download aria-hidden="true"/> تنزيل ملف Excel</ActionButton></StatusNotice>:<ActionButton busy={exportBusy==='create'} onClick={()=>void createExport()}>إنشاء ملف Excel</ActionButton>}</div></section><ActionButton variant="quiet" onClick={()=>setRefresh(n=>n+1)}>تحديث النتائج المقبولة</ActionButton></>:null}
 <nav className="context-actions"><a href={`/day?kind=${kind}`}>عمل اليوم</a>{kind==='company'?<a href="/monitoring?kind=company">المتابعة</a>:null}<a href={`/account?kind=${kind}`}>حسابي</a></nav>
 </main>;
}
