import {expect,test} from '@playwright/test';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import type {components} from '../../packages/api-client/src/schema.js';

const fixture='http://127.0.0.1:3037';
test.afterAll(async()=>{await Promise.all([writeFile('.local/phase-37-browser.stop','stop'),writeFile('.local/phase-37-web.stop','stop')]);});
test('filtered report creates, downloads and reauthorizes a real formula-safe workbook',async({page,request})=>{
 const info=await(await request.get(`${fixture}/__fixture/info`)).json() as {workdayId:string;formulaName:string};await page.goto(`/__fixtures/report-export?kind=company&workdayId=${info.workdayId}`);await expect(page.getByRole('heading',{name:'تمت معالجة 1 من 2 شحنة'})).toBeVisible();
 await page.getByLabel('النتيجة',{exact:true}).selectOption('full');await page.getByRole('button',{name:'عرض التقرير',exact:true}).click();await expect(page.getByRole('heading',{name:'تمت معالجة 1 من 1 شحنة'})).toBeVisible();
 const creationResponse=page.waitForResponse(response=>response.request().method()==='POST'&&response.url().includes('/exports?kind=company'));await page.getByRole('button',{name:'إنشاء ملف Excel',exact:true}).click();const publicStatus=await(await creationResponse).json() as components['schemas']['ReportExportStatus'];await expect(page.getByText('ملف Excel جاهز',{exact:true})).toBeVisible();await page.screenshot({path:'output/playwright/phase-37-export-ready.png',fullPage:true});
 const downloadPromise=page.waitForEvent('download'),downloadResponse=page.waitForResponse(response=>response.url().includes(`/report-exports/${publicStatus.exportId}/download`));await page.getByRole('button',{name:/تنزيل ملف Excel/}).click();const [download,response]=await Promise.all([downloadPromise,downloadResponse]),path=await download.path();expect(response.status()).toBe(200);expect(download.suggestedFilename()).toMatch(/^tawsel-workday-.*\.xlsx$/);expect(path).toBeTruthy();
 const bytes=await readFile(path!);expect(bytes.subarray(0,2).toString()).toBe('PK');const inspected=JSON.parse((await promisify(execFile)(process.execPath,['--import','tsx','scripts/inspect-report-export.ts',path!])).stdout) as {snapshotId:string;outcomeFilter:string;sheets:{name:string;rows:number}[];rows:{recipientName:string;recipientCellType:number;outcome:string}[]};expect(inspected.rows).toHaveLength(1);expect(inspected.rows[0]).toMatchObject({recipientName:info.formulaName,recipientCellType:3,outcome:'تسليم كامل'});expect(inspected.outcomeFilter).toBe('تسليم كامل');
 expect((await request.post(`${fixture}/__fixture/revoke-export`)).ok()).toBe(true);const deniedResponse=page.waitForResponse(response=>response.url().includes(`/report-exports/${publicStatus.exportId}/download`));await page.getByRole('button',{name:/تنزيل ملف Excel/}).click();const denied=await deniedResponse;expect(denied.status()).toBe(403);await expect(page.getByRole('alert')).toContainText('Access unavailable for this operation or scope');
 await mkdir('.local',{recursive:true});await writeFile('.local/phase-37-browser-evidence.json',JSON.stringify({evidenceClass:'Actual Chromium/Fastify/isolated PostgreSQL/XLSX; authenticated principal is a labelled fixture, not Keycloak or a physical device',workdayId:info.workdayId,export:publicStatus,downloadStatus:response.status(),revokedDownloadStatus:denied.status(),fileName:download.suggestedFilename(),snapshotId:inspected.snapshotId,sheets:inspected.sheets,formulaText:{value:inspected.rows[0]!.recipientName,type:'string'}},null,2));
});
