import {expect,test,type Page} from '@playwright/test';
import {mkdir,mkdtemp,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
async function choose(page:Page,name:string){await page.getByRole('list',{name:'قائمة المحطات المتاحة'}).getByRole('button',{name:new RegExp(name)}).click();}
async function options(page:Page){const summary=page.getByText('خيارات المهمة',{exact:true});if(await summary.locator('..').getAttribute('open')===null)await summary.click();}
async function actions(page:Page){return page.evaluate(async()=>{const db=await new Promise<IDBDatabase>((ok,fail)=>{const r=indexedDB.open('tawsel-local-work');r.onsuccess=()=>ok(r.result);r.onerror=()=>fail(r.error);});try{return await new Promise<Record<string,unknown>[]>((ok,fail)=>{const r=db.transaction('actions').objectStore('actions').getAll();r.onsuccess=()=>ok(r.result);r.onerror=()=>fail(r.error);});}finally{db.close();}});}
test.afterAll(async()=>{await writeFile('.local/phase-30-browser.stop','stop');});
test('B2B fixed reasons, immutable offline restart/replay, correction history and actual-arrival no-answer',async({playwright,request})=>{
 const info=await(await request.get('http://127.0.0.1:3030/__fixture/info')).json();
 const profile=await mkdtemp(resolve('.local/interop-browser-')),settings={baseURL:'http://localhost:5173',viewport:{width:390,height:844},locale:'ar-EG',timezoneId:'Africa/Cairo',reducedMotion:'reduce' as const,serviceWorkers:'allow' as const};
 let context=await playwright.chromium.launchPersistentContext(profile,settings);
 try{
 let page=await context.newPage();await page.goto('/login/company');await page.getByLabel('كود الشركة (مطلوب)').fill(info.companyCode);await page.getByRole('button',{name:'متابعة',exact:true}).click();await page.getByRole('button',{name:'متابعة تسجيل الدخول'}).click();await page.locator('#username').fill(info.companyUser);await page.locator('#password').fill(info.password);await page.locator('#kc-login').click();
 await page.goto('/prepare?kind=company');await expect(page.getByText('خطة جاهزة')).toBeVisible();await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await page.getByRole('button',{name:'ابدأ الجولة'}).click();await expect(page.getByRole('heading',{name:'المحطة الحالية'})).toBeVisible();
 await choose(page,'عميل الجزئي');await page.getByRole('button',{name:'اتجه للعميل'}).click();await page.getByRole('button',{name:'وصلت',exact:true}).click();await options(page);await page.getByRole('button',{name:'تسليم بعض القطع'}).click();await page.getByLabel('القطع المسلّمة — قميص').fill('2');await page.getByLabel('السبب',{exact:true}).selectOption('missing-pieces');await expect(page.getByText(/لا يغيّر عدد القطع/)).toBeVisible();await page.getByRole('button',{name:'تأكيد النتيجة والتحصيل'}).click();await expect(page.getByText(/تم تأكيد النتيجة والتحصيل من الخادم/)).toBeVisible();
 await page.getByRole('link',{name:'العمل المؤجل والنتائج السابقة'}).click();await page.getByLabel('المهمة',{exact:true}).selectOption(info.taskIds.partial);await page.getByRole('link',{name:'مراجعة النتيجة وتصحيح التسجيل'}).click();await page.getByLabel('القطع المسلّمة — قميص').fill('1');await page.getByLabel('السبب',{exact:true}).selectOption('other');await page.getByLabel('تفصيل السبب (حتى ٥٠٠ حرف)').fill('اللون مختلف عن الطلب');await page.getByRole('button',{name:'حفظ التصحيح'}).click();await expect(page.getByText('تم تأكيد التغيير من الخادم.')).toBeVisible();await expect(page.getByRole('heading',{name:'النتيجة الأصلية'})).toBeVisible();
 await mkdir('output/playwright/interop-2026-10-10',{recursive:true});await page.screenshot({path:'output/playwright/interop-2026-10-10/correction.png',fullPage:true});
 await page.getByRole('link',{name:'العودة للسجل',exact:true}).click();await page.getByRole('link',{name:'العودة للجولة'}).click();await choose(page,'عميل الرفض');await options(page);await page.getByRole('button',{name:'رفض الاستلام',exact:true}).click();await page.getByLabel('السبب',{exact:true}).selectOption('other');await expect(page.getByRole('button',{name:'تأكيد النتيجة والتحصيل'})).toBeDisabled();await page.getByLabel('تفصيل السبب (حتى ٥٠٠ حرف)').fill('العميل لم يعد يحتاج الشحنة');
 await context.setOffline(true);await page.getByRole('button',{name:'تأكيد النتيجة والتحصيل'}).click();await expect(page.getByText('محفوظ على الهاتف',{exact:true})).toBeVisible();const saved=await actions(page),exact=JSON.stringify(saved);expect(saved.some(a=>JSON.stringify(a).includes('العميل لم يعد يحتاج الشحنة')&&JSON.stringify(a).includes('2.0.0'))).toBe(true);
 await context.close();context=await playwright.chromium.launchPersistentContext(profile,settings);await context.setOffline(true);page=await context.newPage();await page.goto('/rounds/current?kind=company');await expect(page.getByText('محفوظ على الهاتف',{exact:true})).toBeVisible();expect(JSON.stringify(await actions(page))).toBe(exact);
 await context.setOffline(false);await page.goto('/local-work?kind=company');await expect.poll(async()=>{const s=await(await request.get('http://127.0.0.1:3030/__fixture/state')).json();return s.outcomes.filter((o:{task_id:string})=>o.task_id===info.taskIds.paid).length;}).toBe(1);
 expect(JSON.stringify(await actions(page))).toBe(exact);await page.goto('/rounds/current?kind=company');await choose(page,'عميل الشحن');await page.getByRole('button',{name:'اتجه للعميل'}).click();await page.getByRole('button',{name:'وصلت',exact:true}).click();await page.getByRole('button',{name:'لم يرد العميل',exact:true}).click();await expect(page.getByText(/تم تسجيل عدم الرد من الخادم/)).toBeVisible();
 const state=await(await request.get('http://127.0.0.1:3030/__fixture/state')).json(),no=state.outcomes.find((o:{task_id:string})=>o.task_id===info.taskIds.unpaid);expect(no.arrival).not.toBeNull();expect(no.collection).toMatchObject({reported:null,shipping:{amountMinor:0},shippingStatus:'not-attempted'});expect(state.outcomes.filter((o:{task_id:string})=>o.task_id===info.taskIds.partial).map((o:{rejection:{code:string}})=>o.rejection.code)).toEqual(['missing-pieces','other']);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:'output/playwright/interop-2026-10-10/no-answer.png',fullPage:true});
 await writeFile('docs/verification/interoperability-browser-2026-10-10.json',JSON.stringify({classification:'Actual isolated Keycloak8185, disposable PostgreSQL, production PWA/Chromium/IndexedDB and browser-process restart; controlled routing; no native Shahn/physical-device claim',browser:context.browser()?.version(),offlineActions:saved,state},null,2)+'\n');
 }finally{await context.close();}
});
