import {readFile,writeFile,access,readdir} from 'node:fs/promises';
import {loadContracts,checkReferences,createValidator,validateExamples,checkCatalog} from './contracts.mjs';

const read=path=>readFile(path,'utf8');
const owners=JSON.parse(await read('docs/verification/implementation-owners.json'));
const evidence=phase=>phase===39?'docs/verification/deployment.md':phase===40?'docs/verification/restore.md':`docs/phase-${String(phase).padStart(2,'0')}-evidence.md`;
const matrix=await read('docs/phases/coverage-matrix.md');
const requirements=matrix.split(/(?=^### R-\d+)/m).slice(1).map(section=>({
 id:section.match(/^### (R-\d+)/)[1],title:section.match(/\*\*(.+?)\*\*/)[1],
 decisions:[...section.matchAll(/D-\d+/g)].map(m=>m[0]),
 phases:[...section.match(/- Owner phases: (.+)/)[1].matchAll(/\[P(\d+)\]/g)].map(m=>Number(m[1]))
}));
if(requirements.length!==65||new Set(requirements.map(r=>r.id)).size!==65)throw new Error('Expected all 65 requirements');
const decisionRows=(await read('docs/phases/decision-map.md')).split('\n').filter(line=>/^\| D-\d+ \|/.test(line));
if(decisionRows.length!==112)throw new Error('Expected all 112 decisions');
for(let i=1;i<=112;i++)if(!decisionRows.some(line=>line.startsWith(`| D-${String(i).padStart(2,'0')} |`)))throw new Error(`Missing D-${i}`);
for(const line of decisionRows)for(const id of line.matchAll(/coverage-matrix.md#(r-\d+)/g))if(!requirements.some(r=>r.id.toLowerCase()===id[1]))throw new Error(`Unmapped decision: ${line}`);
for(let phase=1;phase<=42;phase++){
 const owner=owners[phase];if(!owner?.code.length||!owner.tests.length)throw new Error(`Missing implementation/test owner P${phase}`);
 for(const path of [...owner.code,...owner.tests,evidence(phase)])await access(path);
 if(!(await read(evidence(phase))).trim())throw new Error(`Empty evidence P${phase}`);
}
const bundle=await loadContracts(),validator=createValidator(bundle);
checkReferences(bundle);validateExamples(bundle,validator);checkCatalog(bundle,validator);
const actions=await read('docs/ui-actions.md');
const apiOperations=new Map();
for(const [path,item] of Object.entries(bundle.api.paths))for(const [method,op] of Object.entries(item))if(op?.operationId)apiOperations.set(op.operationId,{method:method.toUpperCase(),path});
const source=[];
async function visit(directory){for(const entry of await readdir(directory,{withFileTypes:true})){const path=`${directory}/${entry.name}`;if(entry.isDirectory())await visit(path);else if(/\.tsx?$/.test(path))source.push({path,text:await read(path)});}}
for(const directory of ['apps/api/src','apps/web/src','apps/mock-erp/src','packages/api-client/src'])await visit(directory);
const operations=bundle.catalog.operations.map(operation=>{
 if(!actions.includes('`'+operation.id+'`'))throw new Error(`Missing UI/effect mapping: ${operation.id}`);
 const owner=owners[operation.ownerPhase];
 if(operation.kind.startsWith('http-')&&operation.lifecycle!=='designed'&&!apiOperations.has(operation.id)&&operation.delivery!=='issuer-hosted'&&operation.id!=='workspace.getHealth')throw new Error(`Missing HTTP contract: ${operation.id}`);
 return {...operation,...apiOperations.get(operation.id),implementationOwner:owner.code,tests:owner.tests,evidence:evidence(operation.ownerPhase),literalReferences:source.filter(s=>s.text.includes(operation.id)).map(s=>s.path)};
});
const report={schemaVersion:1,classification:'Traceability and canonical checks; runtime route/transaction/browser proof is recorded separately in phase-42-evidence.md.',requirements:requirements.length,decisions:decisionRows.length,schemas:Object.keys(bundle.schemas).length,examples:{valid:bundle.examples.filter(x=>x.valid).length,invalid:bundle.examples.filter(x=>!x.valid).length},httpOperations:apiOperations.size,operations};
const link=path=>`[${path}](../../${path})`;
const lines=['# Final requirement execution ledger','',
 'Generated by `node scripts/handoff-audit.mjs`. All 65 requirements retain their original phase owner and concrete implementation/test paths. [Decision amendments](../phases/decision-map.md) cover D-01–D-112. [Operation audit](contract-audit.json) records every HTTP/event/local/internal entry; [UI actions](../ui-actions.md) records role/state/surface ownership.','',
 '**Status vocabulary:** designed = specification; implemented = actual code; verified locally = evidence under the cited local conditions; verified on target = deployed host/device evidence; owner-reviewed = recorded human review. These columns are independent. No target or owner acceptance is inferred from code, file existence or a passing local test. [Final commands/results](../phase-42-evidence.md), [A–P readiness](pilot-readiness.md).','',
 '| Requirement | Implementation owner and applicable checks | Local evidence | Target / owner status and remaining condition |','| --- | --- | --- | --- |'];
for(const requirement of requirements){
 const phases=[...new Set(requirement.phases)];
 const references=phases.map(p=>`P${String(p).padStart(2,'0')}: ${owners[p].code.map(link).join(', ')}; checks ${owners[p].tests.map(link).join(', ')}`).join('<br>');
 const limits=[...new Set(phases.map(p=>owners[p].limit).filter(Boolean))].join(' ');
 lines.push(`| [${requirement.id}](../phases/coverage-matrix.md#${requirement.id.toLowerCase()}) ${requirement.title} | ${references} | ${phases.map(p=>link(evidence(p))).join(', ')}; implemented/specification and local verification only as recorded there | Target: unverified. Owner: review pending. ${limits||'No unresolved local feature defect identified by this audit; target acceptance remains separate.'} |`);
}
lines.push('','## Cross-cutting obligations','',
 'R-19/R-21/R-22/R-23/R-28 require live provider/profile/dataset verification. R-07 requires external recovery-email verification. R-39–R-42/R-59 require physical Android/Chrome and iPhone/Safari, installed/reopen/update/storage checks and actual elapsed offline observation. R-45/R-61 retain the measured higher-load ERP miss. R-55/R-57/R-59 require owner/device review. R-60/R-62 require target deployment and separate-failure-domain restore. These are outstanding requirements, even where their local implementation passed.','',
 'R-63 is an enforced scope boundary (no GPS, billing, learning, native mobile or real ERP build), not a speculative launch feature. R-64/R-65 include this handoff and its reproducible evidence; future real ERP mapping and connector work remain owned by that separate project. Reserved `progress.snapshot` and `integration.applicationReported` webhook names are unavailable; implemented HTTP snapshot/checkpoint reads satisfy their current use cases.','');
const outputs={'docs/verification/contract-audit.json':JSON.stringify(report,null,2)+'\n','docs/verification/requirement-ledger.md':lines.join('\n')};
for(const [path,content] of Object.entries(outputs)){
 if(process.argv.includes('--check')){if(await read(path)!==content)throw new Error(`Stale handoff audit: ${path}`);}
 else await writeFile(path,content);
}
console.log(`Handoff traceability: ${requirements.length} requirements, ${decisionRows.length} decisions, ${operations.length} operations, ${apiOperations.size} HTTP methods; canonical references/examples and all owner/evidence paths resolve.`);
