import {readFile,writeFile,readdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import YAML from 'yaml';
const date='2026-10-10',path=`docs/verification/interoperability-ledger-${date}.json`;
const json=async p=>JSON.parse(await readFile(p,'utf8'));
const optional=async p=>{try{return await json(p);}catch(e){if(e.code==='ENOENT')return null;throw e;}};
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
const api=YAML.parse(await readFile('contracts/openapi.yaml','utf8')),catalog=(await json('contracts/operations.json')).operations,valid=await json('contracts/examples/valid.json');
const service=Object.entries(api.paths).flatMap(([p,m])=>Object.entries(m).filter(([,v])=>v.security?.some(s=>s.ProvisioningService)).map(([method,v])=>({id:v.operationId,method:method.toUpperCase(),path:p,definition:v})));
if(service.length!==44)throw Error('Reviewed service inventory changed');
const sourcePath=`docs/verification/integration-local-${date}.json`,source=await optional(sourcePath),prePath=`docs/verification/interoperability-predeparture-${date}.json`,pre=await optional(prePath),returnPath=`docs/verification/interoperability-examples-${date}.json`,returned=await optional(returnPath);
const reasonPath=`docs/verification/interoperability-reasons-${date}.json`,reason=await optional(reasonPath);
const tests=[];for(const p of ['apps/api/test/integration','apps/mock-erp/test/integration'])for(const name of await readdir(p))if(name.endsWith('.test.ts'))tests.push({path:`${p}/${name}`,text:await readFile(`${p}/${name}`,'utf8')});
const fixtures=id=>valid.filter(v=>v.data?.operationId===id).map(v=>({fixtureId:v.id,schema:v.schema,actionId:v.data.actionId,classification:'generated valid shape; no runtime acceptance inferred'}));
const witnesses=id=>{
 const result=(source?.sourceCommands??[]).filter(c=>c.operationId===id).map(c=>({classification:'fresh separate-process public HTTP reference source',proof:sourcePath,actionId:c.actionId,status:c.status,receiptId:c.result?.receipt?.receiptId}));
 if(['integration.getDeliveryStatus','integration.replayEvents','integration.getAppliedCheckpoint'].includes(id))for(const report of source?.appliedReports??[])result.push({classification:'fresh public HTTP read with concrete recipient aggregate; see source runner and recorded signed events/checkpoints',proof:sourcePath,aggregate:report.report?.checkpoint.aggregate,reportedAt:report.report?.reportedAt,status:'read-positive'});
 for(const [proof,p,command] of [[prePath,pre,pre?.request],[returnPath,returned,returned?.requests?.redispatch]])if(command?.operationId===id)result.push({classification:'fresh authenticated public HTTP injection with real PostgreSQL',proof,actionId:command.actionId,receiptId:p.result.receipt.receiptId,status:p.result.receipt.businessStatus});
 return result;
};
const operations=service.map(o=>({operationId:o.id,method:o.method,path:o.path,capability:catalog.find(c=>c.id===o.id)?.capability??'see canonical security',newInDelta:o.id==='dispatch.relocateBeforeDeparture',businessSelection:o.id==='intake.setUrgencyBeforeDeparture'?'conditional adapter only; no added ERP business action':'retained source boundary',generatedFixtures:fixtures(o.id),freshPublicWitnesses:witnesses(o.id),regressionSuites:tests.filter(t=>t.text.includes(o.id)).map(t=>t.path),regressionClassification:'real disposable database and route/domain suites; matching operation string is traceability, not proof of every HTTP case or a per-command identity',historicalEvidence:{date:'2026-10-08',publisherPin:'32aad03e8a1a04ac36b95a5a77ab7bf8f7623ada',reference:'owner archive: attachments/docs/verification/P22/OPERATION-EVENT-EVIDENCE.md',scope:'selected historical subset only; not a fresh run or closed acceptance'},status:witnesses(o.id).length?'local-public-positive-exercised; native-full-row-pending':'local-regression-and-fixtures; fresh-public-full-row-pending',pending:['native Shahn conformance and adoption','joint authority/negative/recovery case review','separate-server business/operations acceptance']}));
const eventRows=[];for(const version of ['1','2']){
 const schema=`contracts/events/sender-event.v${version}.schema.json`,s=await json(schema);
 for(const variant of s.oneOf){const eventType=variant.properties.eventType.const,payloadVersion=variant.properties.payloadVersion.const;
  const fixtureRows=valid.filter(v=>v.data?.eventType===eventType&&v.data?.payloadVersion===payloadVersion).map(v=>({fixtureId:v.id,schema:v.schema,eventId:v.data.eventId,classification:'generated schema fixture'}));
  const fresh=(source?.eventWitnesses??[]).filter(e=>e.eventType===eventType&&e.payloadVersion===payloadVersion).map(e=>({...e,proof:sourcePath,classification:'fresh signed producer/independent HTTP reference consumer; applied reports in proof'}));
  for(const [proof,p] of [[prePath,pre],[returnPath,returned],[reasonPath,reason]])for(const e of p?.senderWitness?.events??[])if(e.eventType===eventType&&e.payloadVersion===payloadVersion)fresh.push({...e,proof,classification:'fresh signed HTTP into separate durable reference receiver; atomic independent projection checked'});
  const producer=[];for(const [proof,p]of [[prePath,pre],[returnPath,returned],[reasonPath,reason]])for(const e of p?.replay?.events??[])if(e.eventType===eventType&&e.payloadVersion===payloadVersion)producer.push({proof,eventId:e.eventId,aggregate:e.aggregate,classification:'real committed producer plus schema-valid public replay/reconciliation'});
  eventRows.push({eventType,payloadVersion,schema,generatedFixtures:fixtureRows,freshSignedWitnesses:fresh,freshProducerWitnesses:producer,status:fresh.length?'local-reference-signed-positive; native-full-row-pending':producer.length?'local-producer-positive; native-signed-full-row-pending':'generated-fixtures-and-regression; fresh-signed-full-row-pending',historicalEvidence:payloadVersion==='1.0.0'?{date:'2026-10-08',reference:'owner archive: attachments/docs/verification/P22/OPERATION-EVENT-EVIDENCE.md',scope:'15/27 historical sender types exercised; no blanket closure; other rows pending'}:null,pending:['native closed union reader before writer','native projection/duplicate/gap/replay/checkpoint/correction cases','actual separate-server acceptance']});
 }
}
if(eventRows.length!==31)throw Error('Reviewed sender variant inventory changed');
const bootstrap=catalog.find(o=>o.id==='integration.bindSource');
const provenance={initialTawselCommit:'bbc977b6662a9093eabd0039661f4992a0e5f292',shahnCurrentReadOnlyCommit:'ccd685cdbd20b24b3a20f437e6949ba04ff93b84',shahnApprovedPublisherPin:'32aad03e8a1a04ac36b95a5a77ab7bf8f7623ada',sourceCommit:source?.sourceCommit??null,sourceSha256:source?.sourceSha256??null,consumerRuntimeSha256:source?.consumerRuntimeSha256??null,applicationImageDigest:null,deployedRuntimeIdentity:null,originalByteHashRule:'SHA256 on original bytes; no LF normalization'};
try{provenance.ownerArchiveSha256=hash(await readFile('../integration-handoff-2026-10-10.zip'));}catch(e){if(e.code!=='ENOENT')throw e;}
const ledger={date,classification:'Tawsel implementation conformance evidence; no native Shahn, physical custody, human acceptance or deployment closure inferred',provenance,inventory:{startingServiceOperations:43,newServiceOperations:1,serviceOperations:44,operatorBootstrap:1,startingSenderVariants:27,newVersionedVariants:4,senderVariants:31,distinctSenderTypes:28},operatorBootstrap:{operationId:bootstrap.id,method:bootstrap.method,path:bootstrap.path,authority:'ProvisioningOperator only; exact subjects, no global token export',generatedFixtures:fixtures(bootstrap.id),helperProof:`docs/verification/installation-helper-${date}.json`,helperClassification:'protected directory and simulated public-response recovery; not native installation',status:'local-bootstrap-regression-and-helper; actual-installation-pending'},operations,senderVariants:eventRows,requirements:[{id:'fixed-b2b-reasons',local:'implemented: UI/immutable capture/server/history/correction/signed union/replay/reconciliation',proof:[returnPath,`docs/verification/interoperability-browser-${date}.json`],external:'native reader/display/stock/financial adoption pending'},{id:'actual-arrival-no-answer',local:'implemented and browser exercised; accepted arrival retained, reported null, payment zero/not-attempted',proof:`docs/verification/interoperability-browser-${date}.json`,external:'actual device/user acceptance pending'},{id:'predeparture-A-to-B',local:'implemented with explicit withdrawal, received assertion, immutable cycle branch and dual source scope',proof:prePath,external:'native actual transfer/receipt and unknown-outcome custody fence pending'},{id:'returned-A-to-B',local:'implemented using actual unallocated Tawsel receipt balance; B return and A history preserved',proof:returnPath,external:'native ERP receipt/mapping/concurrency acceptance pending'},{id:'automatic-enrollment',local:'incomplete; no secure issuer writer ownership inventory established',shipped:'operator-assisted-exact-subjects with nonsecret pending EnrollmentRequest',external:'trusted issuer namespace/writers/admin boundary and independent marker verification absent'},{id:'independent-installation',local:'helper, metadata/schema/backend verifier implemented',external:'native administrator UI, signed-callback activation, HTTPS443 deployment and joint acceptance pending'}]};
await writeFile(path,JSON.stringify(ledger,null,2)+'\n');console.log(`Dated ledger: ${operations.length} service rows + operator, ${eventRows.length} sender variants; open gates retained.`);
