import {createHash} from 'node:crypto';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {spawnSync} from 'node:child_process';
import {resolve,join} from 'node:path';

const baseline=resolve('.local/snapshots/20260930T145930Z');
const git=(...args)=>{const r=spawnSync('git',args,{encoding:'utf8'});if(r.status!==0)throw new Error('Git state unavailable');return r.stdout.trim();};
if(git('status','--porcelain'))throw new Error('Commit tracked changes before generating the handoff');
const commit=git('rev-parse','HEAD'),branch=git('branch','--show-current');
const remote=git('ls-remote','origin',`refs/heads/${branch}`).split(/\s+/)[0];
if(remote!==commit)throw new Error('Push the final branch before generating the handoff');
const inventory=JSON.parse(await readFile(join(baseline,'runtime-inventory.json'),'utf8'));
const assets=JSON.parse(await readFile(join(baseline,'asset-sha256.json'),'utf8'));
const imagePath=process.argv[2];
const imageReport=imagePath?JSON.parse(await readFile(resolve(imagePath),'utf8')):null;
if(imageReport&&(imageReport.commit!==commit||imageReport.appOrigin!=='https://app.switch2tech.cloud'))throw new Error('Image digest report must match the pushed commit and pilot app origin');
if(imageReport){
  const names=['runtime','web','issuer','gateway','vroom','database','nominatim'];
  if(names.some(name=>!new RegExp(`^ghcr\\.io/7ossam26/tawsel-[a-z-]+@sha256:[a-f0-9]{64}$`).test(imageReport.images?.[name]??'')))throw new Error('Image report must contain seven immutable GHCR digest references');
}
const output=resolve('.local/dokploy-handoff',new Date().toISOString().replace(/[:.]/g,'-'));
await mkdir(output,{recursive:true});
const write=async(name,value)=>writeFile(join(output,name),typeof value==='string'?value:JSON.stringify(value,null,2)+'\n',{flag:'wx'});
const sourceUrl=`https://github.com/7ossam26/tawsel-routing/tree/${commit}`;
const images=inventory.docker.images.map(image=>({references:image.references,repoDigests:image.repoDigests,sizeBytes:image.sizeBytes}));
const safeInventory={schemaVersion:1,capturedAtUtc:inventory.capturedAtUtc,purpose:'Local inventory only; not a restorable backup',baselineCommit:inventory.git.head,docker:{clientVersion:inventory.docker.engine.clientVersion,serverVersion:inventory.docker.engine.serverVersion,composeVersion:inventory.docker.engine.composeVersion,architecture:inventory.docker.engine.architecture,cpus:inventory.docker.engine.cpus,memoryBytes:inventory.docker.engine.memoryBytes,containers:inventory.docker.containers.map(c=>({name:c.name,imageReference:c.imageReference,state:c.state,health:c.health,restartPolicy:c.restartPolicy,memoryLimitBytes:c.memoryLimitBytes,shmSizeBytes:c.shmSizeBytes,publishedPorts:c.publishedPorts.map(p=>({containerPort:p.containerPort,hostPort:p.hostPort,hostIp:p.hostIp})),mounts:c.mounts.map(m=>({type:m.type,destination:m.destination,readWrite:m.readWrite}))})),images,nominatimImportFinishedMarker:inventory.docker.nominatimImportFinishedMarker,statsSample:inventory.docker.statsSample.map(s=>({name:s.name,memory:s.memory,memoryPercent:s.memoryPercent}))},assetSummary:inventory.assetSummary};
const safeAssets=assets.filter(a=>/^(?:data\/|\.local\/maps\/)/.test(a.path)&&!a.path.includes('..')).map(a=>({path:a.path,sizeBytes:a.sizeBytes,sha256:a.sha256}));
await write('02-LOCAL-INVENTORY.json',safeInventory);
await write('03-ASSETS-SHA256.json',safeAssets);
await write('00-START-HERE-AR.md',`# تعليمات للشات الجديد: رفع Tawsel خطوة بخطوة\n\nأنت ChatGPT في شات جديد، وليس لديك وصول تلقائي لجهازي أو ملفاتي أو SSH أو Dokploy. سأرفق ملفات هذه الحزمة وأعطيك رابط المصدر المثبت: ${sourceUrl}. اقرأ المرفقات والملفات ذات الصلة في هذا الـcommit، وراجع توثيق Dokploy الرسمي https://docs.dokploy.com/llms.txt وhttps://docs.dokploy.com/docs/api عند الحاجة. لو لم تستطع فتح ملف في GitHub، اطلب مني إرفاقه تحديدًا؛ لا تخمن محتواه.\n\nمهمتك أن ترشدني لتشغيل Engine، PostgreSQL، Tawsel، Keycloak والبوابة، وMock ERP على Dokploy لتجربة مباشرة للفريق. استخدم الدومينات app.switch2tech.cloud وauth.switch2tech.cloud وmock.switch2tech.cloud؛ admin.switch2tech.cloud لإدارة Dokploy فقط. قواعد التطبيق والهوية والـMock تبدأ فارغة؛ ننقل OSRM والخريطة وNominatim المستورد فقط بعد التحقق من البصمات. البيانات الكبيرة والـvolumes غير مرفقة في الشات.\n\n**في كل رد: خطوة تنفيذية واحدة فقط.** قل أين أنفذها (Windows أو SSH أو Dokploy UI)، وما النتيجة المتوقعة، وما الدليل المنقح الذي أرجعه لك. انتظر ردي قبل الخطوة التالية، وشخّص أي فشل قبل الاستمرار. لا تطلب مني نسخ كلمات مرور أو tokens أو ملفات env أو مفاتيح أو dump في الشات. عندما أحتاج إدخال سر، وجّهني لإدخاله مباشرة في مكانه الآمن واطلب فقط تأكيدًا أو نتيجة فحص منقحة.\n\nابدأ بجرد الـVPS الفعلي: RAM وCPU والمساحة والـarchitecture وإصدار Dokploy وحالة Docker والشبكات، ثم تحقق من DNS وHTTPS للنطاقات، GHCR وصلاحية السحب، وتخزين S3 خارجي وSMTP. قارن الاستهلاك المتوقع مع الجرد المحلي؛ لو المساحة أو الذاكرة لا تكفي، أوقف خطوات النشر واذكر الموارد المطلوبة. افحص Compose الفعلي عبر Dokploy Preview Compose. لا تشغل Compose القديم في جذر الريبو، ولا تعرض قاعدة البيانات أو Engine أو Keycloak Admin أو منافذ خامًا.\n\nتسلسل العمل: جهز الشبكات والـvolumes والأسرار؛ تحقق من نجاح workflow بناء الصور لنفس الـcommit وحمّل تقرير digests إن لم يكن في MANIFEST؛ انقل ملفات OSRM والخريطة وافحص SHA-256، وصدّر volume Nominatim وهي متوقفة ثم استعدها وافحص import-finished؛ شغل PostgreSQL 18 مع TLS وpgBackRest، ثم Keycloak واستورد الـrealms، ثم migrations والأصول والتطبيق، ثم حسابات الفريق والـMock. تحقق من نسخة خارج السيرفر ومن استرجاع معزول قبل فتح النطاقات، ثم نفذ طلبًا كاملًا من Mock ERP حتى وصول النتيجة وفحص Admin/realm master المحجوبين.\n\nملف الجرد المحلي دليل حالة فقط وليس backup. لا تعتبر deployment في حالة queued أو healthcheck بسيطًا دليل نجاح. احتفظ بتقرير مختصر لكل مرحلة وبنقطة توقف واضحة عند الخطأ.\n`);
await write('01-CURRENT-STATE-AR.md',`# الحالة المثبتة\n\n- مصدر الكود: ${sourceUrl}\n- جرد التشغيل المحلي: ${inventory.capturedAtUtc}؛ حالة وصفية فقط وليست backup.\n- تجربة Mock ERP المحلية اكتملت لطلب موزع ومنفذ مع رجوع الأحداث، لكن تشغيل Dokploy على الـVPS لم يبدأ بعد.\n- المصدر العام لا يحتوي ملفات OSRM المعالجة أو PMTiles أو volume Nominatim أو أسرار التشغيل. ملف SHA-256 المرفق يغطي ملفات data والخرائط فقط؛ Nominatim يحتاج تصديرًا باردًا مستقلًا.\n- الدومينات المعتمدة للتجربة: app.switch2tech.cloud وauth.switch2tech.cloud وmock.switch2tech.cloud. حسابات الفريق تُنشأ على Keycloak وتُقيد في Mock ERP بواسطة subject allowlist.\n- صور الإصدار: ${imageReport?'تقرير digest مرفق داخل MANIFEST.':'تحقق من تشغيل workflow Build pilot images على هذا الـcommit وحمّل release-images.json قبل نشر التطبيق؛ تقرير الصور غير مرفق بعد.'}\n- حدود الخريطة المرئية الحالية هي نطاق القاهرة الموجود في manifest؛ التوجيه المعالج يغطي ملف مصر المستخدم محليًا.\n`);
await write('04-DOKPLOY-NOTES-AR.md',`# ملاحظات Dokploy المؤكدة\n\n- راجع التوثيق الرسمي: https://docs.dokploy.com/llms.txt وhttps://docs.dokploy.com/docs/api وhttps://docs.dokploy.com/docs/core/docker-compose\n- متغيرات Compose في واجهة Dokploy تُحفظ في .env للاستبدال؛ لا تدخل تلقائيًا للحاويات. استخدم env_file أو mapping صريح بحسب Compose.\n- استخدم Domains في Dokploy للمنافذ الداخلية web:8080 وissuer-gateway:8080 وmock:3010، ثم Preview Compose للتأكد من Traefik والشبكات الفعلية: https://docs.dokploy.com/docs/core/docker-compose/domains\n- ملفات الأسرار يجب أن تبقى في تخزين Dokploy المستمر خارج checkout المتجدد؛ اختبر مسارات file-backed secrets في Preview Compose. لا تنسخ محتواها للشات.\n- Dokploy Volume Backups تدعم named volumes فقط، لا bind mounts: https://docs.dokploy.com/docs/core/volume-backups\n- Keycloak public proxy paths موضحة في https://www.keycloak.org/server/reverseproxy ؛ افحص رفض /admin و/realms/master فعليًا.\n- PostgreSQL/pgBackRest: https://pgbackrest.org/user-guide.html ؛ لا يكفي نجاح backup job وحده من دون اختبار restore.\n`);
await write('05-DEPLOYMENT-PREREQUISITES-AR.md',`# بيانات مطلوبة قبل أي نشر\n\nاكتب القيم غير السرية فقط في الشات الجديد: مواصفات الـVPS المرصودة، إصدار Dokploy، نوع معمارية CPU، مساحة القرص المتاحة، أسماء الشبكات والـvolumes، حالة DNS للنطاقات الثلاثة، ومزوّد S3 وSMTP دون مفاتيح. أدخل كلمات المرور والمفاتيح داخل Dokploy أو ملفات محمية على السيرفر فقط.\n\nبوابة التوقف: لو الذاكرة/القرص لا تكفي Engine والتطبيق وPostgreSQL وKeycloak وعمليات النسخ/الاسترجاع، لا ترفع الخدمات. الجرد المحلي سجل نحو 6.25 GiB لـEngine في عينة واحدة؛ هذا ليس قياس ذروة.\n\nملفات النشر في الـcommit: deploy/engine.compose.yaml ثم deploy/database.compose.yaml ثم deploy/compose.yaml ثم deploy/mock-public.compose.yaml. استخدم أمثلة env المقابلة كقائمة مفاتيح فقط ولا ترفع نسخًا مُعبأة إلى GitHub أو الشات. فحص أول تثبيت يستخدم kind=initial، وفحص فتح الدومينات kind=go-live، والترقيات اللاحقة kind=upgrade.\n\nملفات الأصول الكبيرة تُنقل مباشرة بين مخزن محمي والـVPS وتُفحص SHA-256 هناك بأداة scripts/pilot-asset-verify.mjs. أداة scripts/pilot-nominatim-export.mjs توقف حاوية Nominatim المحلية، تصدّر الـvolume، تعيد تشغيل الحاوية وتنتج تقرير SHA-256. لا ترفق الأرشيف في الشات، وتحقق من علامـة import-finished في الوجهة قبل بدء الخدمة. فعّل جدولة pgBackRest الموجودة في scripts/pilot-pgbackrest-backup.sh وdeploy/tawsel-pgbackrest-backup.* واختبر restore معزولًا.\n`);
const names=['00-START-HERE-AR.md','01-CURRENT-STATE-AR.md','02-LOCAL-INVENTORY.json','03-ASSETS-SHA256.json','04-DOKPLOY-NOTES-AR.md','05-DEPLOYMENT-PREREQUISITES-AR.md'];
const files=Object.fromEntries(await Promise.all(names.map(async name=>[name,createHash('sha256').update(await readFile(join(output,name))).digest('hex')])));
await write('MANIFEST.json',{schemaVersion:1,generatedAtUtc:new Date().toISOString(),sourceCommit:commit,sourceUrl,sourceBranch:branch,snapshotCapturedAtUtc:inventory.capturedAtUtc,appOrigin:'https://app.switch2tech.cloud',authOrigin:'https://auth.switch2tech.cloud',mockOrigin:'https://mock.switch2tech.cloud',imageReport:imageReport??{status:'pending-github-actions-workflow'},filesSha256:files});
console.log(output);
