// Generated by npm run contracts:generate. P07 session endpoints; other business operations remain designed.
export interface paths {
    "/api/account/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read own activation/recovery state. */
        get: operations["account.getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Issue browser-bound CSRF token; grants no account access. */
        get: operations["session.bootstrap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Validate OIDC callback and establish independent Tawsel session. */
        get: operations["session.completeLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/company": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve company code to safe login context; company selection grants no authority. */
        post: operations["session.resolveCompany"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read current issuer-validated session and P06 access context. Display fields are never request authority. */
        get: operations["session.getContext"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Begin OIDC authorization code / PKCE login. */
        post: operations["session.beginLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End session; P35 adds durable pending-action/account-switch guards. */
        post: operations["session.logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/recover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Initiate email recovery without account enumeration. */
        post: operations["account.beginRecovery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh authenticated backend session; no tokens in URLs. */
        post: operations["session.refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a separate B2C phone/password identity with recovery email. */
        post: operations["account.registerIndependent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Server-resolved access snapshot, implemented internally in P06; session.getContext HTTP remains P07. Source is the stable account or integration UUID. Display guidance only: recheck current permissions, resource scope and lifecycle for every read/write/job/export. No role name conveys authority. */
        AccessContext: {
            branchIds: components["schemas"]["Uuid"][];
            driverId: components["schemas"]["Uuid"] | null;
            effectiveCapabilities: components["schemas"]["Capability"][];
            /** @enum {string} */
            principalKind: "account" | "integration";
            sourceId: components["schemas"]["Uuid"];
            tenantId: components["schemas"]["Uuid"];
            /** @enum {string} */
            tenantKind: "company" | "personal";
        } & (unknown & unknown);
        /** @enum {string} */
        AccountKind: "company" | "personal";
        /**
         * Action envelope v1 — designed
         * @description P05 hash v1 includes every envelope field plus trusted actor identity: sorted object keys, original array order, UTF-8 JSON, no default insertion or Unicode normalization. Keep the immutable envelope across retries; source scope is authenticated and stable across token refresh. A generic valid envelope does not validate or authorize its feature payload.
         */
        "action-envelope.v1.schema": {
            actionId: components["schemas"]["Uuid"];
            baseVersions: components["schemas"]["Versions"];
            context: components["schemas"]["CommandContext"];
            dependsOnActionIds: components["schemas"]["Uuid"][];
            observation: components["schemas"]["Observation"];
            operationId: components["schemas"]["OperationId"];
            /** @description Envelope validation only. Feature owner MUST validate the operation-specific versioned payload before any acceptance. */
            payload: {
                [key: string]: unknown;
            };
            /** @constant */
            payloadVersion: "1.0.0";
            resources: components["schemas"]["ResourceContext"];
            /** @constant */
            schemaVersion: "1.0.0";
        };
        /**
         * Durable command result v1
         * @description P05 verifies this result in the internal PostgreSQL kernel. Authenticated action.getResult HTTP delivery remains designed pending P06-P08. A compacted result preserves the receipt and feature-owned summary; it never permits executing the action again. Full responses last at least 30 days and unresolved work is held.
         */
        "action-result.v1.schema": {
            operationId: components["schemas"]["OperationId"];
            receipt: components["schemas"]["evidence-receipt.v1.schema"];
            response?: {
                body: {
                    [key: string]: unknown;
                };
                status: number;
            };
            /** @enum {unknown} */
            retention: "full" | "compacted";
            /** @description Minimal stable feature identity/revision references, retained for the business-record lifetime; not a copy of the full response or personal contact details. */
            summary: {
                [key: string]: unknown;
            };
        } & (unknown & {
            receipt: {
                /** @enum {unknown} */
                businessStatus?: "accepted" | "rejected" | "review-required";
            };
        });
        ActionEnvelope: components["schemas"]["action-envelope.v1.schema"];
        ActionResult: components["schemas"]["action-result.v1.schema"];
        /** @enum {string} */
        ApplicationStatus: "unknown" | "pending" | "applied" | "failed";
        AuthError: {
            error: {
                /** @enum {string} */
                code: "invalid_request" | "csrf_invalid" | "rate_limited" | "login_failed" | "company_unavailable" | "access_disabled" | "session_expired" | "issuer_unavailable" | "same_account_required" | "phone_invalid";
                message: string;
            };
        };
        BootstrapResponse: {
            csrfToken: string;
        };
        /** @enum {string} */
        BusinessStatus: "pending" | "accepted" | "rejected" | "review-required";
        CallbackQuery: {
            code?: string;
            error?: string;
            error_description?: string;
            iss?: string;
            session_state?: string;
            state: string;
        };
        /** @enum {string} */
        Capability: "monitor.read" | "planning.manage" | "location.review" | "execution.own" | "correction.own" | "reports.read" | "reports.export" | "intake.prepare" | "assignment.manage" | "return.receive" | "return.dispose" | "identity.provision" | "integration.manage" | "diagnostics.read";
        /**
         * @description Explicit user choice overrides the role; inherit (or no exception row) follows the current role value. Missing role grants deny. Applies equally across assigned branches.
         * @enum {string}
         */
        CapabilityEffect: "inherit" | "allow" | "deny";
        /** @description Company-user override vocabulary; ERP provisioning endpoint remains P08. This object cannot grant access by appearing in a request. */
        CapabilityOverride: {
            capability: components["schemas"]["Capability"];
            effect: components["schemas"]["CapabilityEffect"];
        };
        ClockEvidence: {
            estimatedOffsetMilliseconds?: number;
            /** @enum {string} */
            quality: "known" | "uncertain" | "unknown";
        };
        /** @description Body assertions must match authenticated bindings. An asserted actorId is not authentication. */
        CommandContext: components["schemas"]["DeviceContext"] | components["schemas"]["IntegrationContext"];
        CompanyRequest: {
            code: string;
        };
        CompanyResponse: {
            code: string;
            displayName: string;
        };
        ContactSnapshot: {
            externalCustomerReference?: components["schemas"]["SourceReference"];
            name: string;
            phone: string;
        };
        Coordinates: {
            latitude: number;
            longitude: number;
        };
        DeliveryRequirements: {
            instructions?: string;
            /** @enum {string} */
            priority?: "ordinary" | "urgent";
            serviceDurationSeconds?: number;
            timeWindow?: components["schemas"]["TimeWindow"];
        };
        DeliverySnapshot: {
            customer: components["schemas"]["ContactSnapshot"];
            location: components["schemas"]["LocationSnapshot"];
            requirements?: components["schemas"]["DeliveryRequirements"];
            sourceOrderReference?: components["schemas"]["SourceReference"];
            sourceRevision: components["schemas"]["Revision"];
            sourceTaskReference: components["schemas"]["SourceReference"];
        };
        /** @enum {string} */
        DeliveryStatus: "pending" | "sending" | "received" | "failed";
        DeviceContext: {
            accountId: components["schemas"]["Uuid"];
            deviceGeneration: components["schemas"]["Generation"];
            deviceId: components["schemas"]["Uuid"];
            deviceSequence: components["schemas"]["Sequence"];
            /** @constant */
            kind: "device";
            tenantId: components["schemas"]["Uuid"];
        };
        /** Recipient event envelope v1 — designed */
        "envelope.v1.schema": {
            aggregate: {
                id: components["schemas"]["Uuid"];
                recipientSequence: components["schemas"]["Sequence"];
                /** @enum {string} */
                type: "task" | "assignment" | "trip" | "workday" | "return-request" | "integration";
            };
            committedAt: components["schemas"]["UtcInstant"];
            correlation: {
                actionId?: components["schemas"]["Uuid"];
                sourceReference?: components["schemas"]["SourceReference"];
            };
            eventId: components["schemas"]["Uuid"];
            /** @enum {string} */
            eventKind: "transition" | "replacement-snapshot";
            eventType: components["schemas"]["OperationId"];
            /** @description Feature owner supplies event-type/payload-version schema. Envelope acceptance is not business validation. */
            payload: {
                [key: string]: unknown;
            };
            /** @constant */
            payloadVersion: "1.0.0";
            recipientIntegrationId: components["schemas"]["Uuid"];
            resources: components["schemas"]["ResourceContext"];
            /** @constant */
            schemaVersion: "1.0.0";
            snapshotRevision?: components["schemas"]["Revision"];
            tenantId: components["schemas"]["Uuid"];
            versions: components["schemas"]["Versions"];
        } & unknown;
        /** @enum {string} */
        ErrorCode: "validation_failed" | "idempotency_conflict" | "capacity_exceeded" | "invalid_pin" | "unauthorized" | "forbidden_resource" | "lifecycle_forbidden" | "departed_edit_forbidden" | "stale_revision" | "stale_device" | "unsupported_price_allocation" | "dependency_missing" | "dependency_unavailable" | "unassigned_route" | "result_unknown" | "unsupported_schema_version" | "replay_expired" | "correction_dependency_conflict";
        EventEnvelope: components["schemas"]["envelope.v1.schema"];
        /** Durable evidence receipt v1 — designed */
        "evidence-receipt.v1.schema": {
            actionId: components["schemas"]["Uuid"];
            businessStatus: components["schemas"]["BusinessStatus"];
            committedAt?: components["schemas"]["UtcInstant"];
            evidenceStatus: components["schemas"]["EvidenceStatus"];
            problem?: components["schemas"]["Problem"];
            receiptId: components["schemas"]["Uuid"];
            receivedAt: components["schemas"]["UtcInstant"];
            resourceVersions?: components["schemas"]["Versions"];
            /** @constant */
            schemaVersion: "1.0.0";
        } & (unknown & unknown);
        EvidenceReceipt: components["schemas"]["evidence-receipt.v1.schema"];
        /** @enum {string} */
        EvidenceStatus: "received";
        ExternalId: string;
        Generation: number;
        IntegrationContext: {
            assertedActorId?: components["schemas"]["Uuid"];
            integrationId: components["schemas"]["Uuid"];
            /** @constant */
            kind: "integration";
            tenantId: components["schemas"]["Uuid"];
        };
        KindRequest: {
            kind: components["schemas"]["AccountKind"];
        };
        LocationSnapshot: {
            confirmedPin?: components["schemas"]["Coordinates"];
            locationRevision?: components["schemas"]["Revision"];
            originalAddress?: string;
            /** @enum {string} */
            provenance: "source" | "driver-confirmed" | "staff-confirmed";
        } | {
            originalAddress: unknown;
        } | {
            confirmedPin: unknown;
        };
        LoginRequest: {
            companyCode?: string;
            /** @enum {string} */
            intent?: "login" | "register" | "recover";
            kind: components["schemas"]["AccountKind"];
            phone?: string;
            reauthenticate?: boolean;
        };
        /** @description Nonnegative integer minor units, never a decimal amount or arbitrary underpayment. Currency/exponent must match supported source policy; EGP is exponent 2. */
        Money: {
            amountMinor: number;
            currency: string;
            exponent: number;
        } & unknown;
        Observation: {
            clock: components["schemas"]["ClockEvidence"];
            observedAt: components["schemas"]["UtcInstant"] | null;
        };
        OperationId: string;
        PageInfo: {
            nextCursor: string | null;
            snapshotRevision: components["schemas"]["Revision"];
        };
        PageRequest: {
            cursor?: string;
            limit?: number;
        };
        PieceCount: number;
        PositivePieceCount: number;
        Problem: {
            actionId?: components["schemas"]["Uuid"];
            code: components["schemas"]["ErrorCode"];
            correlationId: components["schemas"]["Uuid"];
            detail?: string;
            retryable: boolean;
            status: number;
            title: string;
            /** Format: uri */
            type: string;
        } & (unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown);
        RedirectResponse: {
            /** Format: uri */
            authorizationUrl: string;
        };
        ResourceContext: {
            assignmentId?: components["schemas"]["Uuid"];
            attemptId?: components["schemas"]["Uuid"];
            dispatchCycleId?: components["schemas"]["Uuid"];
            planId?: components["schemas"]["Uuid"];
            stopId?: components["schemas"]["Uuid"];
            taskId?: components["schemas"]["Uuid"];
            tripId?: components["schemas"]["Uuid"];
            workdayId?: components["schemas"]["Uuid"];
        };
        Revision: number;
        SchemaVersion: string;
        Sequence: number;
        SessionContext: {
            access: components["schemas"]["AccessContext"];
            /** Format: date-time */
            expiresAt: string;
            kind: components["schemas"]["AccountKind"];
            loginIdentifier: string;
            /** @constant */
            phoneOwnershipVerified: false;
            recoveryEmailVerified: boolean;
        };
        SourceReference: {
            externalId: components["schemas"]["ExternalId"];
            integrationId: components["schemas"]["Uuid"];
            tenantId: components["schemas"]["Uuid"];
        };
        TimeWindow: {
            earliestAt: components["schemas"]["UtcInstant"];
            latestAt?: components["schemas"]["UtcInstant"];
        };
        /**
         * Format: date-time
         * @description UTC RFC 3339 instant. Does not establish clock accuracy.
         */
        UtcInstant: string;
        /**
         * Format: uuid
         * @description Lowercase UUID; field identity and authenticated relationship checks remain distinct.
         */
        Uuid: string;
        Versions: {
            assignmentGeneration?: components["schemas"]["Generation"];
            deviceGeneration?: components["schemas"]["Generation"];
            outcomeRevision?: components["schemas"]["Revision"];
            resourceRevision?: components["schemas"]["Revision"];
            routeRevision?: components["schemas"]["Revision"];
            snapshotRevision?: components["schemas"]["Revision"];
            sourceRevision?: components["schemas"]["Revision"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "account.getStatus": {
        parameters: {
            query: {
                kind: components["schemas"]["AccountKind"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionContext"];
                };
            };
            /** @description Invalid input or OIDC response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description Session expired; retain local evidence */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description CSRF or current access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description Issuer unavailable; retain local evidence */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
        };
    };
    "session.bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapResponse"];
                };
            };
            /** @description Invalid input or OIDC response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description Session expired; retain local evidence */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description CSRF or current access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description Issuer unavailable; retain local evidence */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
        };
    };
    "session.completeLogin": {
        parameters: {
            query: {
                code?: string;
                error?: string;
                error_description?: string;
                iss?: string;
                session_state?: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fixed same-origin account destination or safe login error; never a request-selected redirect. */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid input or OIDC response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description Session expired; retain local evidence */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description CSRF or current access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description Issuer unavailable; retain local evidence */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
        };
    };
    "session.resolveCompany": {
        parameters: {
            query?: never;
            header: {
                Origin: string;
                "X-CSRF-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyResponse"];
                };
            };
            /** @description Invalid input or OIDC response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description Session expired; retain local evidence */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description CSRF or current access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description Issuer unavailable; retain local evidence */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
        };
    };
    "session.getContext": {
        parameters: {
            query: {
                kind: components["schemas"]["AccountKind"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionContext"];
                };
            };
            /** @description Invalid input or OIDC response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description Session expired; retain local evidence */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description CSRF or current access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description Issuer unavailable; retain local evidence */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
        };
    };
    "session.beginLogin": {
        parameters: {
            query?: never;
            header: {
                Origin: string;
                "X-CSRF-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RedirectResponse"];
                };
            };
            /** @description Invalid input or OIDC response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description Session expired; retain local evidence */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description CSRF or current access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description Issuer unavailable; retain local evidence */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
        };
    };
    "session.logout": {
        parameters: {
            query?: never;
            header: {
                Origin: string;
                "X-CSRF-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KindRequest"];
            };
        };
        responses: {
            /** @description Local session ended. No global ERP logout. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid input or OIDC response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description Session expired; retain local evidence */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description CSRF or current access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description Issuer unavailable; retain local evidence */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
        };
    };
    "account.beginRecovery": {
        parameters: {
            query?: never;
            header: {
                Origin: string;
                "X-CSRF-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RedirectResponse"];
                };
            };
            /** @description Invalid input or OIDC response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description Session expired; retain local evidence */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description CSRF or current access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description Issuer unavailable; retain local evidence */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
        };
    };
    "session.refresh": {
        parameters: {
            query?: never;
            header: {
                Origin: string;
                "X-CSRF-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KindRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionContext"];
                };
            };
            /** @description Invalid input or OIDC response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description Session expired; retain local evidence */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description CSRF or current access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description Issuer unavailable; retain local evidence */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
        };
    };
    "account.registerIndependent": {
        parameters: {
            query?: never;
            header: {
                Origin: string;
                "X-CSRF-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RedirectResponse"];
                };
            };
            /** @description Invalid input or OIDC response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description Session expired; retain local evidence */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description CSRF or current access denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
            /** @description Issuer unavailable; retain local evidence */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthError"];
                };
            };
        };
    };
}
