// Generated by npm run contracts:generate. Designed foundation; no business endpoints.
export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Action envelope v1 — designed */
        "action-envelope.v1.schema": {
            actionId: components["schemas"]["Uuid"];
            baseVersions: components["schemas"]["Versions"];
            context: components["schemas"]["CommandContext"];
            dependsOnActionIds: components["schemas"]["Uuid"][];
            observation: components["schemas"]["Observation"];
            operationId: components["schemas"]["OperationId"];
            /** @description Envelope validation only. Feature owner MUST validate the operation-specific versioned payload before any acceptance. */
            payload: {
                [key: string]: unknown;
            };
            /** @constant */
            payloadVersion: "1.0.0";
            resources: components["schemas"]["ResourceContext"];
            /** @constant */
            schemaVersion: "1.0.0";
        };
        ActionEnvelope: components["schemas"]["action-envelope.v1.schema"];
        /** @enum {string} */
        ApplicationStatus: "unknown" | "pending" | "applied" | "failed";
        /** @enum {string} */
        BusinessStatus: "pending" | "accepted" | "rejected" | "review-required";
        /** @enum {string} */
        Capability: "monitor.read" | "planning.manage" | "location.review" | "execution.own" | "correction.own" | "reports.read" | "reports.export" | "intake.prepare" | "assignment.manage" | "return.receive" | "return.dispose" | "identity.provision" | "integration.manage" | "diagnostics.read";
        ClockEvidence: {
            estimatedOffsetMilliseconds?: number;
            /** @enum {string} */
            quality: "known" | "uncertain" | "unknown";
        };
        /** @description Body assertions must match authenticated bindings. An asserted actorId is not authentication. */
        CommandContext: components["schemas"]["DeviceContext"] | components["schemas"]["IntegrationContext"];
        ContactSnapshot: {
            externalCustomerReference?: components["schemas"]["SourceReference"];
            name: string;
            phone: string;
        };
        Coordinates: {
            latitude: number;
            longitude: number;
        };
        DeliveryRequirements: {
            instructions?: string;
            /** @enum {string} */
            priority?: "ordinary" | "urgent";
            serviceDurationSeconds?: number;
            timeWindow?: components["schemas"]["TimeWindow"];
        };
        DeliverySnapshot: {
            customer: components["schemas"]["ContactSnapshot"];
            location: components["schemas"]["LocationSnapshot"];
            requirements?: components["schemas"]["DeliveryRequirements"];
            sourceOrderReference?: components["schemas"]["SourceReference"];
            sourceRevision: components["schemas"]["Revision"];
            sourceTaskReference: components["schemas"]["SourceReference"];
        };
        /** @enum {string} */
        DeliveryStatus: "pending" | "sending" | "received" | "failed";
        DeviceContext: {
            accountId: components["schemas"]["Uuid"];
            deviceGeneration: components["schemas"]["Generation"];
            deviceId: components["schemas"]["Uuid"];
            deviceSequence: components["schemas"]["Sequence"];
            /** @constant */
            kind: "device";
            tenantId: components["schemas"]["Uuid"];
        };
        /** Recipient event envelope v1 — designed */
        "envelope.v1.schema": {
            aggregate: {
                id: components["schemas"]["Uuid"];
                recipientSequence: components["schemas"]["Sequence"];
                /** @enum {string} */
                type: "task" | "assignment" | "trip" | "workday" | "return-request" | "integration";
            };
            committedAt: components["schemas"]["UtcInstant"];
            correlation: {
                actionId?: components["schemas"]["Uuid"];
                sourceReference?: components["schemas"]["SourceReference"];
            };
            eventId: components["schemas"]["Uuid"];
            /** @enum {string} */
            eventKind: "transition" | "replacement-snapshot";
            eventType: components["schemas"]["OperationId"];
            /** @description Feature owner supplies event-type/payload-version schema. Envelope acceptance is not business validation. */
            payload: {
                [key: string]: unknown;
            };
            /** @constant */
            payloadVersion: "1.0.0";
            recipientIntegrationId: components["schemas"]["Uuid"];
            resources: components["schemas"]["ResourceContext"];
            /** @constant */
            schemaVersion: "1.0.0";
            snapshotRevision?: components["schemas"]["Revision"];
            tenantId: components["schemas"]["Uuid"];
            versions: components["schemas"]["Versions"];
        } & unknown;
        /** @enum {string} */
        ErrorCode: "validation_failed" | "idempotency_conflict" | "capacity_exceeded" | "invalid_pin" | "unauthorized" | "forbidden_resource" | "departed_edit_forbidden" | "stale_revision" | "stale_device" | "unsupported_price_allocation" | "dependency_missing" | "dependency_unavailable" | "unassigned_route" | "result_unknown" | "unsupported_schema_version" | "replay_expired" | "correction_dependency_conflict";
        EventEnvelope: components["schemas"]["envelope.v1.schema"];
        /** Durable evidence receipt v1 — designed */
        "evidence-receipt.v1.schema": {
            actionId: components["schemas"]["Uuid"];
            businessStatus: components["schemas"]["BusinessStatus"];
            committedAt?: components["schemas"]["UtcInstant"];
            evidenceStatus: components["schemas"]["EvidenceStatus"];
            problem?: components["schemas"]["Problem"];
            receiptId: components["schemas"]["Uuid"];
            receivedAt: components["schemas"]["UtcInstant"];
            resourceVersions?: components["schemas"]["Versions"];
            /** @constant */
            schemaVersion: "1.0.0";
        } & (unknown & unknown);
        EvidenceReceipt: components["schemas"]["evidence-receipt.v1.schema"];
        /** @enum {string} */
        EvidenceStatus: "received";
        ExternalId: string;
        Generation: number;
        IntegrationContext: {
            assertedActorId?: components["schemas"]["Uuid"];
            integrationId: components["schemas"]["Uuid"];
            /** @constant */
            kind: "integration";
            tenantId: components["schemas"]["Uuid"];
        };
        LocationSnapshot: {
            confirmedPin?: components["schemas"]["Coordinates"];
            locationRevision?: components["schemas"]["Revision"];
            originalAddress?: string;
            /** @enum {string} */
            provenance: "source" | "driver-confirmed" | "staff-confirmed";
        } | {
            originalAddress: unknown;
        } | {
            confirmedPin: unknown;
        };
        /** @description Nonnegative integer minor units, never a decimal amount or arbitrary underpayment. Currency/exponent must match supported source policy; EGP is exponent 2. */
        Money: {
            amountMinor: number;
            currency: string;
            exponent: number;
        } & unknown;
        Observation: {
            clock: components["schemas"]["ClockEvidence"];
            observedAt: components["schemas"]["UtcInstant"] | null;
        };
        OperationId: string;
        PageInfo: {
            nextCursor: string | null;
            snapshotRevision: components["schemas"]["Revision"];
        };
        PageRequest: {
            cursor?: string;
            limit?: number;
        };
        PieceCount: number;
        PositivePieceCount: number;
        Problem: {
            actionId?: components["schemas"]["Uuid"];
            code: components["schemas"]["ErrorCode"];
            correlationId: components["schemas"]["Uuid"];
            detail?: string;
            retryable: boolean;
            status: number;
            title: string;
            /** Format: uri */
            type: string;
        } & (unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown & unknown);
        ResourceContext: {
            assignmentId?: components["schemas"]["Uuid"];
            attemptId?: components["schemas"]["Uuid"];
            dispatchCycleId?: components["schemas"]["Uuid"];
            planId?: components["schemas"]["Uuid"];
            stopId?: components["schemas"]["Uuid"];
            taskId?: components["schemas"]["Uuid"];
            tripId?: components["schemas"]["Uuid"];
            workdayId?: components["schemas"]["Uuid"];
        };
        Revision: number;
        SchemaVersion: string;
        Sequence: number;
        SourceReference: {
            externalId: components["schemas"]["ExternalId"];
            integrationId: components["schemas"]["Uuid"];
            tenantId: components["schemas"]["Uuid"];
        };
        TimeWindow: {
            earliestAt: components["schemas"]["UtcInstant"];
            latestAt?: components["schemas"]["UtcInstant"];
        };
        /**
         * Format: date-time
         * @description UTC RFC 3339 instant. Does not establish clock accuracy.
         */
        UtcInstant: string;
        /**
         * Format: uuid
         * @description Lowercase UUID; field identity and authenticated relationship checks remain distinct.
         */
        Uuid: string;
        Versions: {
            assignmentGeneration?: components["schemas"]["Generation"];
            deviceGeneration?: components["schemas"]["Generation"];
            outcomeRevision?: components["schemas"]["Revision"];
            resourceRevision?: components["schemas"]["Revision"];
            routeRevision?: components["schemas"]["Revision"];
            snapshotRevision?: components["schemas"]["Revision"];
            sourceRevision?: components["schemas"]["Revision"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
